use crate::v4::Side::{Bottom, Left, Right, Top};
use crate::v4::{BorderSymbol, Side};
use ratatui::widgets::BorderType;
use ratatui::widgets::BorderType::{Double, QuadrantInside, QuadrantOutside, Thick};

pub fn plain_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┞",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┭",
            BorderSymbol::StartCornerProlonged(_, _) => "┬",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            // BorderSymbol::SideOverlap(_, Thick) => "━",
            // BorderSymbol::SideOverlap(_, Double) => "═",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┸",
            BorderSymbol::SideOutward(_, Double) => "╨",
            BorderSymbol::SideOutward(_, _) => "┴",
            BorderSymbol::SideInward(_, Thick) => "┰",
            BorderSymbol::SideInward(_, Double) => "╥",
            BorderSymbol::SideInward(_, _) => "┬",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┐",
            BorderSymbol::EndCornerAngled(_, Thick) => "┦",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┮",
            BorderSymbol::EndCornerProlonged(_, _) => "┬",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "┐",
            BorderSymbol::StartCornerAngled(_, Thick) => "┮",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┦",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┝",
            BorderSymbol::SideOutward(_, Double) => "╞",
            BorderSymbol::SideOutward(_, _) => "├",
            BorderSymbol::SideInward(_, Thick) => "┥",
            BorderSymbol::SideInward(_, Double) => "╡",
            BorderSymbol::SideInward(_, _) => "┤",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┶",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┧",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "└",
            BorderSymbol::StartCornerAngled(_, Thick) => "┟",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┵",
            BorderSymbol::StartCornerProlonged(_, _) => "┴",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╅",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┰",
            BorderSymbol::SideOutward(_, Double) => "╥",
            BorderSymbol::SideOutward(_, _) => "┬",
            BorderSymbol::SideInward(_, Thick) => "┸",
            BorderSymbol::SideInward(_, Double) => "╨",
            BorderSymbol::SideInward(_, _) => "┴",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┧",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┶",
            BorderSymbol::EndCornerProlonged(_, _) => "┴",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┭",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┞",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┥",
            BorderSymbol::SideOutward(_, Double) => "╡",
            BorderSymbol::SideOutward(_, _) => "┤",
            BorderSymbol::SideInward(_, Thick) => "┝",
            BorderSymbol::SideInward(_, Double) => "╞",
            BorderSymbol::SideInward(_, _) => "├",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "└",
            BorderSymbol::EndCornerAngled(_, Thick) => "┵",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┟",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
    }
}

pub fn quadrant_inside_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "▗",
            BorderSymbol::StartCornerAngled(Left, _) => "▐",
            BorderSymbol::StartCornerAngled(Right, _) => "▙",
            BorderSymbol::StartCornerAngled(_, _) => "X",
            BorderSymbol::StartCornerProlonged(Top, _) => "▄",
            BorderSymbol::StartCornerProlonged(Bottom, _) => "▜",
            BorderSymbol::StartCornerProlonged(_, _) => "X",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▚",
            BorderSymbol::SideRegular => "▄",
            BorderSymbol::SideOverlap(_, QuadrantOutside) => "▄",
            BorderSymbol::SideOverlap(_, _) => "█",
            BorderSymbol::SideOutward(Left, _) => "▟",
            BorderSymbol::SideOutward(Right, _) => "▙",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▄",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▙",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▖",
            BorderSymbol::EndCornerAngled(Left, _) => "▟",
            BorderSymbol::EndCornerAngled(Right, _) => "▌",
            BorderSymbol::EndCornerAngled(_, _) => "X",
            BorderSymbol::EndCornerProlonged(Top, _) => "▄",
            BorderSymbol::EndCornerProlonged(Bottom, _) => "▛",
            BorderSymbol::EndCornerProlonged(_, _) => "X",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▞",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "▝",
            BorderSymbol::StartCornerAngled(Left, _) => "▐",
            BorderSymbol::StartCornerAngled(Right, _) => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "X",
            BorderSymbol::StartCornerProlonged(Top, _) => "▟",
            BorderSymbol::StartCornerProlonged(Bottom, _) => "▀",
            BorderSymbol::StartCornerProlonged(_, _) => "X",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▞",
            BorderSymbol::SideRegular => "▀",
            BorderSymbol::SideOverlap(_, QuadrantOutside) => "▀",
            BorderSymbol::SideOverlap(_, _) => "█",
            BorderSymbol::SideOutward(Left, _) => "▜",
            BorderSymbol::SideOutward(Right, _) => "▛",
            BorderSymbol::SideOutward(_, _) => "▛",
            BorderSymbol::SideInward(_, _) => "▄",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▜",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▛",
            BorderSymbol::SideCrossed(_, _, _, _) => "▛",
            BorderSymbol::EndCornerRegular => "▘",
            BorderSymbol::EndCornerAngled(Left, _) => "▜",
            BorderSymbol::EndCornerAngled(Right, _) => "▌",
            BorderSymbol::EndCornerAngled(_, _) => "X",
            BorderSymbol::EndCornerProlonged(Top, _) => "▙",
            BorderSymbol::EndCornerProlonged(Bottom, _) => "▀",
            BorderSymbol::EndCornerProlonged(_, _) => "X",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▚",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "▖",
            BorderSymbol::StartCornerAngled(Top, _) => "▄",
            BorderSymbol::StartCornerAngled(Bottom, _) => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "X",
            BorderSymbol::StartCornerProlonged(Left, _) => "▟",
            BorderSymbol::StartCornerProlonged(Right, _) => "▌",
            BorderSymbol::StartCornerProlonged(_, _) => "X",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▞",
            BorderSymbol::SideRegular => "▌",
            BorderSymbol::SideOverlap(_, QuadrantOutside) => "▌",
            BorderSymbol::SideOverlap(_, _) => "█",
            BorderSymbol::SideOutward(Top, _) => "▙",
            BorderSymbol::SideOutward(Bottom, _) => "▛",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▌",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▙",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▛",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▘",
            BorderSymbol::EndCornerAngled(Top, _) => "▙",
            BorderSymbol::EndCornerAngled(Bottom, _) => "▀",
            BorderSymbol::EndCornerAngled(_, _) => "X",
            BorderSymbol::EndCornerProlonged(Left, _) => "▌",
            BorderSymbol::EndCornerProlonged(Right, _) => "▜",
            BorderSymbol::EndCornerProlonged(_, _) => "X",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▚",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "▗",
            BorderSymbol::StartCornerAngled(Top, _) => "▟",
            BorderSymbol::StartCornerAngled(Bottom, _) => "▄",
            BorderSymbol::StartCornerAngled(_, _) => "X",
            BorderSymbol::StartCornerProlonged(Left, _) => "▐",
            BorderSymbol::StartCornerProlonged(Right, _) => "▛",
            BorderSymbol::StartCornerProlonged(_, _) => "X",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▚",
            BorderSymbol::SideRegular => "▐",
            BorderSymbol::SideOverlap(_, QuadrantOutside) => "▐",
            BorderSymbol::SideOverlap(_, _) => "█",
            BorderSymbol::SideOutward(Top, _) => "▟",
            BorderSymbol::SideOutward(Bottom, _) => "▜",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▐",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▜",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▝",
            BorderSymbol::EndCornerAngled(Top, _) => "▀",
            BorderSymbol::EndCornerAngled(Bottom, _) => "▟",
            BorderSymbol::EndCornerAngled(_, _) => "X",
            BorderSymbol::EndCornerProlonged(Left, _) => "▐",
            BorderSymbol::EndCornerProlonged(Right, _) => "▙",
            BorderSymbol::EndCornerProlonged(_, _) => "X",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▞",
        },
    }
}
