use crate::v4::{BorderSymbol, Side};
use ratatui::widgets::BorderType;

pub fn plain_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┞",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┭",
            BorderSymbol::StartCornerProlonged(_, _) => "┬",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            // BorderSymbol::SideOverlap(_, Thick) => "━",
            // BorderSymbol::SideOverlap(_, Double) => "═",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┸",
            BorderSymbol::SideOutward(_, Double) => "╨",
            BorderSymbol::SideOutward(_, _) => "┴",
            BorderSymbol::SideInward(_, Thick) => "┰",
            BorderSymbol::SideInward(_, Double) => "╥",
            BorderSymbol::SideInward(_, _) => "┬",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┐",
            BorderSymbol::EndCornerAngled(_, Thick) => "┦",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┮",
            BorderSymbol::EndCornerProlonged(_, _) => "┬",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "┐",
            BorderSymbol::StartCornerAngled(_, Thick) => "┮",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┦",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┝",
            BorderSymbol::SideOutward(_, Double) => "╞",
            BorderSymbol::SideOutward(_, _) => "├",
            BorderSymbol::SideInward(_, Thick) => "┥",
            BorderSymbol::SideInward(_, Double) => "╡",
            BorderSymbol::SideInward(_, _) => "┤",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┶",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┧",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "└",
            BorderSymbol::StartCornerAngled(_, Thick) => "┟",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┵",
            BorderSymbol::StartCornerProlonged(_, _) => "┴",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╅",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┰",
            BorderSymbol::SideOutward(_, Double) => "╥",
            BorderSymbol::SideOutward(_, _) => "┬",
            BorderSymbol::SideInward(_, Thick) => "┸",
            BorderSymbol::SideInward(_, Double) => "╨",
            BorderSymbol::SideInward(_, _) => "┴",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┧",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┶",
            BorderSymbol::EndCornerProlonged(_, _) => "┴",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┭",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┞",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┥",
            BorderSymbol::SideOutward(_, Double) => "╡",
            BorderSymbol::SideOutward(_, _) => "┤",
            BorderSymbol::SideInward(_, Thick) => "┝",
            BorderSymbol::SideInward(_, Double) => "╞",
            BorderSymbol::SideInward(_, _) => "├",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "└",
            BorderSymbol::EndCornerAngled(_, Thick) => "┵",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┟",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
    }
}
