use crate::v4::{BorderSymbol, Side};
use ratatui::widgets::BorderType;

pub fn plain_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┞",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┭",
            BorderSymbol::StartCornerProlonged(_, _) => "┬",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┸",
            BorderSymbol::SideOutward(_, Double) => "╨",
            BorderSymbol::SideOutward(_, _) => "┴",
            BorderSymbol::SideInward(_, Thick) => "┰",
            BorderSymbol::SideInward(_, Double) => "╥",
            BorderSymbol::SideInward(_, _) => "┬",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┐",
            BorderSymbol::EndCornerAngled(_, Thick) => "┦",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┮",
            BorderSymbol::EndCornerProlonged(_, _) => "┬",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "└",
            BorderSymbol::StartCornerAngled(_, Thick) => "┟",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┵",
            BorderSymbol::StartCornerProlonged(_, _) => "┴",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╅",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┰",
            BorderSymbol::SideOutward(_, Double) => "╥",
            BorderSymbol::SideOutward(_, _) => "┬",
            BorderSymbol::SideInward(_, Thick) => "┸",
            BorderSymbol::SideInward(_, Double) => "╨",
            BorderSymbol::SideInward(_, _) => "┴",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┧",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┶",
            BorderSymbol::EndCornerProlonged(_, _) => "┴",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "┐",
            BorderSymbol::StartCornerAngled(_, Thick) => "┮",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┦",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┝",
            BorderSymbol::SideOutward(_, Double) => "╞",
            BorderSymbol::SideOutward(_, _) => "├",
            BorderSymbol::SideInward(_, Thick) => "┥",
            BorderSymbol::SideInward(_, Double) => "╡",
            BorderSymbol::SideInward(_, _) => "┤",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "┘",
            BorderSymbol::EndCornerAngled(_, Thick) => "┶",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┧",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "┌",
            BorderSymbol::StartCornerAngled(_, Thick) => "┭",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┞",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┥",
            BorderSymbol::SideOutward(_, Double) => "╡",
            BorderSymbol::SideOutward(_, _) => "┤",
            BorderSymbol::SideInward(_, Thick) => "┝",
            BorderSymbol::SideInward(_, Double) => "╞",
            BorderSymbol::SideInward(_, _) => "├",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "└",
            BorderSymbol::EndCornerAngled(_, Thick) => "┵",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┟",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
    }
}

pub fn rounded_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "╭",
            BorderSymbol::StartCornerAngled(_, Thick) => "┞",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┭",
            BorderSymbol::StartCornerProlonged(_, _) => "┬",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┸",
            BorderSymbol::SideOutward(_, Double) => "╨",
            BorderSymbol::SideOutward(_, _) => "┴",
            BorderSymbol::SideInward(_, Thick) => "┰",
            BorderSymbol::SideInward(_, Double) => "╥",
            BorderSymbol::SideInward(_, _) => "┬",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "╮",
            BorderSymbol::EndCornerAngled(_, Thick) => "┦",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┮",
            BorderSymbol::EndCornerProlonged(_, _) => "┬",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╀",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "╰",
            BorderSymbol::StartCornerAngled(_, Thick) => "┟",
            BorderSymbol::StartCornerAngled(_, _) => "├",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┵",
            BorderSymbol::StartCornerProlonged(_, _) => "┴",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╅",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "─",
            BorderSymbol::SideOverlap(_, _) => "─",
            BorderSymbol::SideOutward(_, Thick) => "┰",
            BorderSymbol::SideOutward(_, Double) => "╥",
            BorderSymbol::SideOutward(_, _) => "┬",
            BorderSymbol::SideInward(_, Thick) => "┸",
            BorderSymbol::SideInward(_, Double) => "╨",
            BorderSymbol::SideInward(_, _) => "┴",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "╂",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "╯",
            BorderSymbol::EndCornerAngled(_, Thick) => "┧",
            BorderSymbol::EndCornerAngled(_, _) => "┤",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┶",
            BorderSymbol::EndCornerProlonged(_, _) => "┴",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "╮",
            BorderSymbol::StartCornerAngled(_, Thick) => "┮",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┦",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╄",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┝",
            BorderSymbol::SideOutward(_, Double) => "╞",
            BorderSymbol::SideOutward(_, _) => "├",
            BorderSymbol::SideInward(_, Thick) => "┥",
            BorderSymbol::SideInward(_, Double) => "╡",
            BorderSymbol::SideInward(_, _) => "┤",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┽",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "╯",
            BorderSymbol::EndCornerAngled(_, Thick) => "┶",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┧",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┾",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "╭",
            BorderSymbol::StartCornerAngled(_, Thick) => "┭",
            BorderSymbol::StartCornerAngled(_, _) => "┬",
            BorderSymbol::StartCornerProlonged(_, Thick) => "┞",
            BorderSymbol::StartCornerProlonged(_, _) => "┤",
            BorderSymbol::StartCornerCrossed(_, Thick, _, Thick) => "╃",
            BorderSymbol::StartCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::StartCornerCrossed(_, _, _, Thick) => "╀",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "┼",
            BorderSymbol::SideRegular => "│",
            BorderSymbol::SideOverlap(_, _) => "│",
            BorderSymbol::SideOutward(_, Thick) => "┥",
            BorderSymbol::SideOutward(_, Double) => "╡",
            BorderSymbol::SideOutward(_, _) => "┤",
            BorderSymbol::SideInward(_, Thick) => "┝",
            BorderSymbol::SideInward(_, Double) => "╞",
            BorderSymbol::SideInward(_, _) => "├",
            BorderSymbol::SideCrossed(_, Thick, _, Thick) => "┿",
            BorderSymbol::SideCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::SideCrossed(_, _, _, Thick) => "┾",
            BorderSymbol::SideCrossed(_, Double, _, Double) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "┼",
            BorderSymbol::EndCornerRegular => "╰",
            BorderSymbol::EndCornerAngled(_, Thick) => "┵",
            BorderSymbol::EndCornerAngled(_, _) => "┴",
            BorderSymbol::EndCornerProlonged(_, Thick) => "┟",
            BorderSymbol::EndCornerProlonged(_, _) => "┤",
            BorderSymbol::EndCornerCrossed(_, Thick, _, Thick) => "╆",
            BorderSymbol::EndCornerCrossed(_, Thick, _, _) => "┽",
            BorderSymbol::EndCornerCrossed(_, _, _, Thick) => "╁",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "┼",
        },
    }
}

pub fn double_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "╔",
            BorderSymbol::StartCornerAngled(_, _) => "╠",
            BorderSymbol::StartCornerProlonged(_, _) => "╦",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╬",
            BorderSymbol::SideRegular => "═",
            BorderSymbol::SideOverlap(_, _) => "═",
            BorderSymbol::SideOutward(_, Plain) => "╧",
            BorderSymbol::SideOutward(_, _) => "╩",
            BorderSymbol::SideInward(_, Plain) => "╤",
            BorderSymbol::SideInward(_, _) => "╦",
            BorderSymbol::SideCrossed(_, Plain, _, Plain) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "╬",
            BorderSymbol::EndCornerRegular => "╗",
            BorderSymbol::EndCornerAngled(_, _) => "╣",
            BorderSymbol::EndCornerProlonged(_, _) => "╦",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╬",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "╚",
            BorderSymbol::StartCornerAngled(_, _) => "╠",
            BorderSymbol::StartCornerProlonged(_, _) => "╩",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╬",
            BorderSymbol::SideRegular => "═",
            BorderSymbol::SideOverlap(_, _) => "═",
            BorderSymbol::SideOutward(_, Plain) => "╤",
            BorderSymbol::SideOutward(_, _) => "╦",
            BorderSymbol::SideInward(_, Plain) => "╧",
            BorderSymbol::SideInward(_, _) => "╩",
            BorderSymbol::SideCrossed(_, Plain, _, Plain) => "╪",
            BorderSymbol::SideCrossed(_, _, _, _) => "╬",
            BorderSymbol::EndCornerRegular => "╝",
            BorderSymbol::EndCornerAngled(_, _) => "╣",
            BorderSymbol::EndCornerProlonged(_, _) => "╩",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╬",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "╗",
            BorderSymbol::StartCornerAngled(_, _) => "╦",
            BorderSymbol::StartCornerProlonged(_, _) => "╣",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╬",
            BorderSymbol::SideRegular => "║",
            BorderSymbol::SideOverlap(_, _) => "║",
            BorderSymbol::SideOutward(_, Plain) => "╟",
            BorderSymbol::SideOutward(_, _) => "╠",
            BorderSymbol::SideInward(_, Plain) => "╢",
            BorderSymbol::SideInward(_, _) => "╣",
            BorderSymbol::SideCrossed(_, Plain, _, Plain) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "╬",
            BorderSymbol::EndCornerRegular => "╝",
            BorderSymbol::EndCornerAngled(_, _) => "╩",
            BorderSymbol::EndCornerProlonged(_, _) => "╣",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╬",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "╔",
            BorderSymbol::StartCornerAngled(_, _) => "╦",
            BorderSymbol::StartCornerProlonged(_, _) => "╣",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╬",
            BorderSymbol::SideRegular => "║",
            BorderSymbol::SideOverlap(_, _) => "║",
            BorderSymbol::SideOutward(_, Plain) => "╢",
            BorderSymbol::SideOutward(_, _) => "╣",
            BorderSymbol::SideInward(_, Plain) => "╟",
            BorderSymbol::SideInward(_, _) => "╠",
            BorderSymbol::SideCrossed(_, Plain, _, Plain) => "╫",
            BorderSymbol::SideCrossed(_, _, _, _) => "╬",
            BorderSymbol::EndCornerRegular => "╚",
            BorderSymbol::EndCornerAngled(_, _) => "╩",
            BorderSymbol::EndCornerProlonged(_, _) => "╣",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╬",
        },
    }
}

pub fn thick_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "┏",
            BorderSymbol::StartCornerAngled(_, Plain | Rounded) => "┢",
            BorderSymbol::StartCornerAngled(_, _) => "┣",
            BorderSymbol::StartCornerProlonged(_, Plain | Rounded) => "┲",
            BorderSymbol::StartCornerProlonged(_, _) => "┳",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "\u{2546}",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, _) => "╈",
            BorderSymbol::StartCornerCrossed(_, _, _, Plain | Rounded) => "╊",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╋",
            BorderSymbol::SideRegular => "━",
            BorderSymbol::SideOverlap(_, _) => "━",
            BorderSymbol::SideOutward(_, Plain | Rounded) => "┷",
            BorderSymbol::SideOutward(_, _) => "┻",
            BorderSymbol::SideInward(_, Plain | Rounded) => "┯",
            BorderSymbol::SideInward(_, _) => "┳",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, Plain | Rounded) => "┿",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, _) => "╈",
            BorderSymbol::SideCrossed(_, _, _, Plain | Rounded) => "╇",
            BorderSymbol::SideCrossed(_, _, _, _) => "╋",
            BorderSymbol::EndCornerRegular => "┓",
            BorderSymbol::EndCornerAngled(_, Plain) => "┪",
            BorderSymbol::EndCornerAngled(_, _) => "┫",
            BorderSymbol::EndCornerProlonged(_, Plain) => "┱",
            BorderSymbol::EndCornerProlonged(_, _) => "┳",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╅",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, _) => "╈",
            BorderSymbol::EndCornerCrossed(_, _, _, Plain | Rounded) => "╉",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╋",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "┗",
            BorderSymbol::StartCornerAngled(_, Plain | Rounded) => "┡",
            BorderSymbol::StartCornerAngled(_, _) => "┣",
            BorderSymbol::StartCornerProlonged(_, Plain | Rounded) => "┺",
            BorderSymbol::StartCornerProlonged(_, _) => "┹",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╄",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, _) => "╇",
            BorderSymbol::StartCornerCrossed(_, _, _, Plain | Rounded) => "╊",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╋",
            BorderSymbol::SideRegular => "━",
            BorderSymbol::SideOverlap(_, _) => "━",
            BorderSymbol::SideOutward(_, Plain | Rounded) => "┯",
            BorderSymbol::SideOutward(_, _) => "┳",
            BorderSymbol::SideInward(_, Plain | Rounded) => "┷",
            BorderSymbol::SideInward(_, _) => "┻",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, Plain | Rounded) => "┿",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, _) => "╇",
            BorderSymbol::SideCrossed(_, _, _, Plain | Rounded) => "╈",
            BorderSymbol::SideCrossed(_, _, _, _) => "╋",
            BorderSymbol::EndCornerRegular => "┛",
            BorderSymbol::EndCornerAngled(_, Plain | Rounded) => "┩",
            BorderSymbol::EndCornerAngled(_, _) => "┫",
            BorderSymbol::EndCornerProlonged(_, Plain | Rounded) => "┹",
            BorderSymbol::EndCornerProlonged(_, _) => "┻",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╃",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, _) => "╇",
            BorderSymbol::EndCornerCrossed(_, _, _, Plain | Rounded) => "╉",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╋",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "┓",
            BorderSymbol::StartCornerAngled(_, Plain | Rounded) => "┱",
            BorderSymbol::StartCornerAngled(_, _) => "┳",
            BorderSymbol::StartCornerProlonged(_, Plain | Rounded) => "┪",
            BorderSymbol::StartCornerProlonged(_, _) => "┫",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╅",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, _) => "╈",
            BorderSymbol::StartCornerCrossed(_, _, _, Plain | Rounded) => "╉",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╋",
            BorderSymbol::SideRegular => "┃",
            BorderSymbol::SideOverlap(_, _) => "┃",
            BorderSymbol::SideOutward(_, Plain | Rounded) => "┠",
            BorderSymbol::SideOutward(_, _) => "┣",
            BorderSymbol::SideInward(_, Plain | Rounded) => "┨",
            BorderSymbol::SideInward(_, _) => "┫",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╂",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, _) => "╉",
            BorderSymbol::SideCrossed(_, _, _, Plain | Rounded) => "╊",
            BorderSymbol::SideCrossed(_, _, _, _) => "╋",
            BorderSymbol::EndCornerRegular => "┛",
            BorderSymbol::EndCornerAngled(_, Plain | Rounded) => "┹",
            BorderSymbol::EndCornerAngled(_, _) => "┻",
            BorderSymbol::EndCornerProlonged(_, Plain | Rounded) => "┩",
            BorderSymbol::EndCornerProlonged(_, _) => "┫",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╃",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, _) => "╉",
            BorderSymbol::EndCornerCrossed(_, _, _, Plain | Rounded) => "╇",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╋",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "┏",
            BorderSymbol::StartCornerAngled(_, Plain | Rounded) => "┲",
            BorderSymbol::StartCornerAngled(_, _) => "┳",
            BorderSymbol::StartCornerProlonged(_, Plain | Rounded) => "┢",
            BorderSymbol::StartCornerProlonged(_, _) => "┣",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "\u{2546}",
            BorderSymbol::StartCornerCrossed(_, Plain | Rounded, _, _) => "╊",
            BorderSymbol::StartCornerCrossed(_, _, _, Plain | Rounded) => "╈",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "╋",
            BorderSymbol::SideRegular => "┃",
            BorderSymbol::SideOverlap(_, _) => "┃",
            BorderSymbol::SideOutward(_, Plain | Rounded) => "┨",
            BorderSymbol::SideOutward(_, _) => "┫",
            BorderSymbol::SideInward(_, Plain | Rounded) => "┠",
            BorderSymbol::SideInward(_, _) => "┣",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╂",
            BorderSymbol::SideCrossed(_, Plain | Rounded, _, _) => "╊",
            BorderSymbol::SideCrossed(_, _, _, Plain | Rounded) => "╉",
            BorderSymbol::SideCrossed(_, _, _, _) => "╋",
            BorderSymbol::EndCornerRegular => "┗",
            BorderSymbol::EndCornerAngled(_, Plain | Rounded) => "┺",
            BorderSymbol::EndCornerAngled(_, _) => "┻",
            BorderSymbol::EndCornerProlonged(_, Plain | Rounded) => "┡",
            BorderSymbol::EndCornerProlonged(_, _) => "┫",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, Plain | Rounded) => "╄",
            BorderSymbol::EndCornerCrossed(_, Plain | Rounded, _, _) => "╊",
            BorderSymbol::EndCornerCrossed(_, _, _, Plain | Rounded) => "╇",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "╋",
        },
    }
}

pub fn quadrant_inside_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;
    use BorderType::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "▗",
            BorderSymbol::StartCornerAngled(Left, QuadrantOutside) => "▙",
            BorderSymbol::StartCornerAngled(Right, QuadrantOutside) => "▐",
            BorderSymbol::StartCornerAngled(Left, QuadrantInside) => "▐",
            BorderSymbol::StartCornerAngled(Right, QuadrantInside) => "▙",
            BorderSymbol::StartCornerAngled(_, _) => "▐",
            BorderSymbol::StartCornerProlonged(Top, QuadrantOutside) => "▄",
            BorderSymbol::StartCornerProlonged(Bottom, QuadrantOutside) => "▄",
            BorderSymbol::StartCornerProlonged(Top, QuadrantInside) => "▄",
            BorderSymbol::StartCornerProlonged(Bottom, QuadrantInside) => "▜",
            BorderSymbol::StartCornerProlonged(_, _) => "▄",
            BorderSymbol::StartCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▟",
            BorderSymbol::StartCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▚",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▟",
            BorderSymbol::SideRegular => "▄",
            BorderSymbol::SideOverlap(_, QuadrantInside) => "█",
            BorderSymbol::SideOverlap(_, _) => "▄",
            BorderSymbol::SideOutward(Left, QuadrantOutside) => "▙",
            BorderSymbol::SideOutward(Right, QuadrantOutside) => "▟",
            BorderSymbol::SideOutward(Left, _) => "▟",
            BorderSymbol::SideOutward(Right, _) => "▙",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▄",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▙",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▖",
            BorderSymbol::EndCornerAngled(Left, QuadrantOutside) => "▌",
            BorderSymbol::EndCornerAngled(Right, QuadrantOutside) => "▟",
            BorderSymbol::EndCornerAngled(Left, QuadrantInside) => "▟",
            BorderSymbol::EndCornerAngled(Right, QuadrantInside) => "▌",
            BorderSymbol::EndCornerAngled(_, _) => "▌",
            BorderSymbol::EndCornerProlonged(Top, QuadrantOutside) => "▛",
            BorderSymbol::EndCornerProlonged(Bottom, QuadrantOutside) => "▄",
            BorderSymbol::EndCornerProlonged(Top, QuadrantInside) => "▄",
            BorderSymbol::EndCornerProlonged(Bottom, QuadrantInside) => "▛",
            BorderSymbol::EndCornerProlonged(_, _) => "▄",
            BorderSymbol::EndCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▙",
            BorderSymbol::EndCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▞",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▙",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "▝",
            BorderSymbol::StartCornerAngled(Left, QuadrantOutside) => "▛",
            BorderSymbol::StartCornerAngled(Right, QuadrantOutside) => "▐",
            BorderSymbol::StartCornerAngled(Left, QuadrantInside) => "▐",
            BorderSymbol::StartCornerAngled(Right, QuadrantInside) => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "▐",
            BorderSymbol::StartCornerProlonged(Top, QuadrantOutside) => "▀",
            BorderSymbol::StartCornerProlonged(Bottom, QuadrantOutside) => "▀",
            BorderSymbol::StartCornerProlonged(Top, QuadrantInside) => "▟",
            BorderSymbol::StartCornerProlonged(Bottom, QuadrantInside) => "▀",
            BorderSymbol::StartCornerProlonged(_, _) => "▀",
            BorderSymbol::StartCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▜",
            BorderSymbol::StartCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▞",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▜",
            BorderSymbol::SideRegular => "▀",
            BorderSymbol::SideOverlap(_, QuadrantInside) => "█",
            BorderSymbol::SideOverlap(_, _) => "▀",
            BorderSymbol::SideOutward(Left, QuadrantOutside) => "▛",
            BorderSymbol::SideOutward(Right, QuadrantOutside) => "▜",
            BorderSymbol::SideOutward(Left, _) => "▜",
            BorderSymbol::SideOutward(Right, _) => "▛",
            BorderSymbol::SideOutward(_, _) => "▛",
            BorderSymbol::SideInward(_, _) => "▄",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▜",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▛",
            BorderSymbol::SideCrossed(_, _, _, _) => "▛",
            BorderSymbol::EndCornerRegular => "▘",
            BorderSymbol::EndCornerAngled(Left, QuadrantOutside) => "▌",
            BorderSymbol::EndCornerAngled(Right, QuadrantOutside) => "▜",
            BorderSymbol::EndCornerAngled(Left, QuadrantInside) => "▜",
            BorderSymbol::EndCornerAngled(Right, QuadrantInside) => "▌",
            BorderSymbol::EndCornerAngled(_, _) => "▌",
            BorderSymbol::EndCornerProlonged(Top, QuadrantOutside) => "▀",
            BorderSymbol::EndCornerProlonged(Bottom, QuadrantOutside) => "▙",
            BorderSymbol::EndCornerProlonged(Top, QuadrantInside) => "▙",
            BorderSymbol::EndCornerProlonged(Bottom, QuadrantInside) => "▀",
            BorderSymbol::EndCornerProlonged(_, _) => "▀",
            BorderSymbol::EndCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▛",
            BorderSymbol::EndCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▚",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▛",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "▖",
            BorderSymbol::StartCornerAngled(Top, QuadrantOutside) => "▛",
            BorderSymbol::StartCornerAngled(Bottom, QuadrantOutside) => "▄",
            BorderSymbol::StartCornerAngled(Top, QuadrantInside) => "▄",
            BorderSymbol::StartCornerAngled(Bottom, QuadrantInside) => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "▄",
            BorderSymbol::StartCornerProlonged(Left, QuadrantOutside) => "▌",
            BorderSymbol::StartCornerProlonged(Right, QuadrantOutside) => "▌",
            BorderSymbol::StartCornerProlonged(Left, QuadrantInside) => "▟",
            BorderSymbol::StartCornerProlonged(Right, QuadrantInside) => "▌",
            BorderSymbol::StartCornerProlonged(_, _) => "▌",
            BorderSymbol::StartCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▙",
            BorderSymbol::StartCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▞",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▙",
            BorderSymbol::SideRegular => "▌",
            BorderSymbol::SideOverlap(_, QuadrantInside) => "█",
            BorderSymbol::SideOverlap(_, _) => "▌",
            BorderSymbol::SideOutward(Top, QuadrantOutside) => "▛",
            BorderSymbol::SideOutward(Bottom, QuadrantOutside) => "▙",
            BorderSymbol::SideOutward(Top, _) => "▙",
            BorderSymbol::SideOutward(Bottom, _) => "▛",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▌",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▙",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▛",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▘",
            BorderSymbol::EndCornerAngled(Top, QuadrantOutside) => "▄",
            BorderSymbol::EndCornerAngled(Bottom, QuadrantOutside) => "▙",
            BorderSymbol::EndCornerAngled(Top, QuadrantInside) => "▙",
            BorderSymbol::EndCornerAngled(Bottom, QuadrantInside) => "▀",
            BorderSymbol::EndCornerAngled(_, _) => "▀",
            BorderSymbol::EndCornerProlonged(Left, QuadrantOutside) => "▌",
            BorderSymbol::EndCornerProlonged(Right, QuadrantOutside) => "▜",
            BorderSymbol::EndCornerProlonged(Left, QuadrantInside) => "▌",
            BorderSymbol::EndCornerProlonged(Right, QuadrantInside) => "▜",
            BorderSymbol::EndCornerProlonged(_, _) => "▌",
            BorderSymbol::EndCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▛",
            BorderSymbol::EndCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▚",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▛",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "▗",
            BorderSymbol::StartCornerAngled(Top, QuadrantOutside) => "▄",
            BorderSymbol::StartCornerAngled(Bottom, QuadrantOutside) => "▟",
            BorderSymbol::StartCornerAngled(Top, QuadrantInside) => "▟",
            BorderSymbol::StartCornerAngled(Bottom, QuadrantInside) => "▄",
            BorderSymbol::StartCornerAngled(_, _) => "▄",
            BorderSymbol::StartCornerProlonged(Left, QuadrantOutside) => "▐",
            BorderSymbol::StartCornerProlonged(Right, QuadrantOutside) => "▐",
            BorderSymbol::StartCornerProlonged(Left, QuadrantInside) => "▐",
            BorderSymbol::StartCornerProlonged(Right, QuadrantInside) => "▛",
            BorderSymbol::StartCornerProlonged(_, _) => "▐",
            BorderSymbol::StartCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▟",
            BorderSymbol::StartCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▚",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▟",
            BorderSymbol::SideRegular => "▐",
            BorderSymbol::SideOverlap(_, QuadrantInside) => "█",
            BorderSymbol::SideOverlap(_, _) => "▐",
            BorderSymbol::SideOutward(Top, QuadrantOutside) => "▜",
            BorderSymbol::SideOutward(Bottom, QuadrantOutside) => "▟",
            BorderSymbol::SideOutward(Top, _) => "▟",
            BorderSymbol::SideOutward(Bottom, _) => "▜",
            BorderSymbol::SideOutward(_, _) => "X",
            BorderSymbol::SideInward(_, _) => "▐",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▜",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▝",
            BorderSymbol::EndCornerAngled(Top, QuadrantOutside) => "▟",
            BorderSymbol::EndCornerAngled(Bottom, QuadrantOutside) => "▀",
            BorderSymbol::EndCornerAngled(Top, QuadrantInside) => "▀",
            BorderSymbol::EndCornerAngled(Bottom, QuadrantInside) => "▟",
            BorderSymbol::EndCornerAngled(_, _) => "▀",
            BorderSymbol::EndCornerProlonged(Left, QuadrantOutside) => "▙",
            BorderSymbol::EndCornerProlonged(Right, QuadrantOutside) => "▐",
            BorderSymbol::EndCornerProlonged(Left, QuadrantInside) => "▐",
            BorderSymbol::EndCornerProlonged(Right, QuadrantInside) => "▙",
            BorderSymbol::EndCornerProlonged(_, _) => "▐",
            BorderSymbol::EndCornerCrossed(_, QuadrantOutside, _, QuadrantOutside) => "▜",
            BorderSymbol::EndCornerCrossed(_, QuadrantInside, _, QuadrantInside) => "▞",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▜",
        },
    }
}

pub fn quadrant_outside_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "▛",
            BorderSymbol::StartCornerProlonged(_, _) => "▛",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▛",
            BorderSymbol::SideRegular => "▀",
            BorderSymbol::SideOverlap(_, _) => "▀",
            BorderSymbol::SideOutward(_, _) => "▀",
            BorderSymbol::SideInward(Left, _) => "▛",
            BorderSymbol::SideInward(Right, _) => "▜",
            BorderSymbol::SideInward(_, _) => "X",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▛",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▜",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▜",
            BorderSymbol::EndCornerAngled(_, _) => "▜",
            BorderSymbol::EndCornerProlonged(_, _) => "▜",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▜",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "▙",
            BorderSymbol::StartCornerAngled(_, _) => "▙",
            BorderSymbol::StartCornerProlonged(_, _) => "▙",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▙",
            BorderSymbol::SideRegular => "▄",
            BorderSymbol::SideOverlap(_, _) => "▄",
            BorderSymbol::SideOutward(Left, _) => "▄",
            BorderSymbol::SideOutward(Right, _) => "▄",
            BorderSymbol::SideOutward(_, _) => "▄",
            BorderSymbol::SideInward(Left, _) => "▙",
            BorderSymbol::SideInward(Right, _) => "▟",
            BorderSymbol::SideInward(_, _) => "X",
            BorderSymbol::SideCrossed(Left, _, _, _) => "▙",
            BorderSymbol::SideCrossed(Right, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▟",
            BorderSymbol::EndCornerAngled(_, _) => "▟",
            BorderSymbol::EndCornerProlonged(_, _) => "▟",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▟",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "▜",
            BorderSymbol::StartCornerAngled(_, _) => "▜",
            BorderSymbol::StartCornerProlonged(_, _) => "▜",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▜",
            BorderSymbol::SideRegular => "▐",
            BorderSymbol::SideOverlap(_, _) => "▐",
            BorderSymbol::SideOutward(_, _) => "▐",
            BorderSymbol::SideInward(Top, _) => "▜",
            BorderSymbol::SideInward(Bottom, _) => "▟",
            BorderSymbol::SideInward(_, _) => "X",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▜",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▟",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▜",
            BorderSymbol::EndCornerAngled(_, _) => "▜",
            BorderSymbol::EndCornerProlonged(_, _) => "▜",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▜",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "▛",
            BorderSymbol::StartCornerAngled(_, _) => "▛",
            BorderSymbol::StartCornerProlonged(_, _) => "▛",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "▛",
            BorderSymbol::SideRegular => "▌",
            BorderSymbol::SideOverlap(_, _) => "▌",
            BorderSymbol::SideOutward(_, _) => "▌",
            BorderSymbol::SideInward(Top, _) => "▛",
            BorderSymbol::SideInward(Bottom, _) => "▙",
            BorderSymbol::SideInward(_, _) => "X",
            BorderSymbol::SideCrossed(Top, _, _, _) => "▛",
            BorderSymbol::SideCrossed(Bottom, _, _, _) => "▙",
            BorderSymbol::SideCrossed(_, _, _, _) => "X",
            BorderSymbol::EndCornerRegular => "▙",
            BorderSymbol::EndCornerAngled(_, _) => "▙",
            BorderSymbol::EndCornerProlonged(_, _) => "▙",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "▙",
        },
    }
}

pub fn ascii_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "+",
            BorderSymbol::StartCornerAngled(_, _) => "+",
            BorderSymbol::StartCornerProlonged(_, _) => "+",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "+",
            BorderSymbol::SideRegular => "-",
            BorderSymbol::SideOverlap(_, _) => "-",
            BorderSymbol::SideOutward(_, _) => "+",
            BorderSymbol::SideInward(_, _) => "+",
            BorderSymbol::SideCrossed(_, _, _, _) => "+",
            BorderSymbol::EndCornerRegular => "+",
            BorderSymbol::EndCornerAngled(_, _) => "+",
            BorderSymbol::EndCornerProlonged(_, _) => "+",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "+",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "+",
            BorderSymbol::StartCornerAngled(_, _) => "+",
            BorderSymbol::StartCornerProlonged(_, _) => "+",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "+",
            BorderSymbol::SideRegular => "-",
            BorderSymbol::SideOverlap(_, _) => "-",
            BorderSymbol::SideOutward(_, _) => "+",
            BorderSymbol::SideInward(_, _) => "+",
            BorderSymbol::SideCrossed(_, _, _, _) => "+",
            BorderSymbol::EndCornerRegular => "+",
            BorderSymbol::EndCornerAngled(_, _) => "+",
            BorderSymbol::EndCornerProlonged(_, _) => "+",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "+",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "+",
            BorderSymbol::StartCornerAngled(_, _) => "+",
            BorderSymbol::StartCornerProlonged(_, _) => "+",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "+",
            BorderSymbol::SideRegular => "|",
            BorderSymbol::SideOverlap(_, _) => "|",
            BorderSymbol::SideOutward(_, _) => "+",
            BorderSymbol::SideInward(_, _) => "+",
            BorderSymbol::SideCrossed(_, _, _, _) => "+",
            BorderSymbol::EndCornerRegular => "+",
            BorderSymbol::EndCornerAngled(_, _) => "+",
            BorderSymbol::EndCornerProlonged(_, _) => "+",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "+",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "+",
            BorderSymbol::StartCornerAngled(_, _) => "+",
            BorderSymbol::StartCornerProlonged(_, _) => "+",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "+",
            BorderSymbol::SideRegular => "|",
            BorderSymbol::SideOverlap(_, _) => "|",
            BorderSymbol::SideOutward(_, _) => "+",
            BorderSymbol::SideInward(_, _) => "+",
            BorderSymbol::SideCrossed(_, _, _, _) => "+",
            BorderSymbol::EndCornerRegular => "+",
            BorderSymbol::EndCornerAngled(_, _) => "+",
            BorderSymbol::EndCornerProlonged(_, _) => "+",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "+",
        },
    }
}

pub fn star_symbol(side: Side, glyph: BorderSymbol) -> &'static str {
    use crate::v4::Side::*;

    match side {
        Top => match glyph {
            BorderSymbol::StartCornerRegular => "*",
            BorderSymbol::StartCornerAngled(_, _) => "*",
            BorderSymbol::StartCornerProlonged(_, _) => "*",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "*",
            BorderSymbol::SideRegular => "*",
            BorderSymbol::SideOverlap(_, _) => "*",
            BorderSymbol::SideOutward(_, _) => "*",
            BorderSymbol::SideInward(_, _) => "*",
            BorderSymbol::SideCrossed(_, _, _, _) => "*",
            BorderSymbol::EndCornerRegular => "*",
            BorderSymbol::EndCornerAngled(_, _) => "*",
            BorderSymbol::EndCornerProlonged(_, _) => "*",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "*",
        },
        Bottom => match glyph {
            BorderSymbol::StartCornerRegular => "*",
            BorderSymbol::StartCornerAngled(_, _) => "*",
            BorderSymbol::StartCornerProlonged(_, _) => "*",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "*",
            BorderSymbol::SideRegular => "*",
            BorderSymbol::SideOverlap(_, _) => "*",
            BorderSymbol::SideOutward(_, _) => "*",
            BorderSymbol::SideInward(_, _) => "*",
            BorderSymbol::SideCrossed(_, _, _, _) => "*",
            BorderSymbol::EndCornerRegular => "*",
            BorderSymbol::EndCornerAngled(_, _) => "*",
            BorderSymbol::EndCornerProlonged(_, _) => "*",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "*",
        },
        Right => match glyph {
            BorderSymbol::StartCornerRegular => "*",
            BorderSymbol::StartCornerAngled(_, _) => "*",
            BorderSymbol::StartCornerProlonged(_, _) => "*",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "*",
            BorderSymbol::SideRegular => "*",
            BorderSymbol::SideOverlap(_, _) => "*",
            BorderSymbol::SideOutward(_, _) => "*",
            BorderSymbol::SideInward(_, _) => "*",
            BorderSymbol::SideCrossed(_, _, _, _) => "*",
            BorderSymbol::EndCornerRegular => "*",
            BorderSymbol::EndCornerAngled(_, _) => "*",
            BorderSymbol::EndCornerProlonged(_, _) => "*",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "*",
        },
        Left => match glyph {
            BorderSymbol::StartCornerRegular => "*",
            BorderSymbol::StartCornerAngled(_, _) => "*",
            BorderSymbol::StartCornerProlonged(_, _) => "*",
            BorderSymbol::StartCornerCrossed(_, _, _, _) => "*",
            BorderSymbol::SideRegular => "*",
            BorderSymbol::SideOverlap(_, _) => "*",
            BorderSymbol::SideOutward(_, _) => "*",
            BorderSymbol::SideInward(_, _) => "*",
            BorderSymbol::SideCrossed(_, _, _, _) => "*",
            BorderSymbol::EndCornerRegular => "*",
            BorderSymbol::EndCornerAngled(_, _) => "*",
            BorderSymbol::EndCornerProlonged(_, _) => "*",
            BorderSymbol::EndCornerCrossed(_, _, _, _) => "*",
        },
    }
}
