use crate::JointPos::{End, ProlongEnd, ProlongStart, Start};
use crate::JointSide::{Bottom, Left, Right, Top};
use crate::{Joint, JointPos, JointScale, JointSide};
use ratatui::buffer::Buffer;
use ratatui::layout::{Position, Rect};
use ratatui::widgets::BorderType;
use ratatui::widgets::BorderType::{
    Double, Plain, QuadrantInside, QuadrantOutside, Rounded, Thick,
};

pub fn render_joint(border: BorderType, mut joint: Joint, area: Rect, buf: &mut Buffer) {
    // normalize before finding the glyph
    let n_pos = match joint.side {
        JointSide::Top | JointSide::Bottom => match joint.pos {
            JointPos::ProlongStart => 0,
            JointPos::Start => 0,
            JointPos::Pos(n) => {
                if n == 0 {
                    joint.pos = JointPos::Start;
                } else if n == area.width - 1 {
                    joint.pos = JointPos::End;
                }
                n
            }
            JointPos::End => area.width - 1,
            JointPos::ProlongEnd => area.width - 1,
        },
        JointSide::Right | JointSide::Left => match joint.pos {
            JointPos::ProlongStart => 0,
            JointPos::Start => 0,
            JointPos::Pos(n) => {
                if n == 0 {
                    joint.pos = JointPos::Start;
                } else if n == area.height - 1 {
                    joint.pos = JointPos::End;
                }
                n
            }
            JointPos::End => area.height - 1,
            JointPos::ProlongEnd => area.height - 1,
        },
    };

    let sym = match border {
        BorderType::Plain => plain_joint(joint),
        BorderType::Rounded => plain_joint(joint),
        BorderType::Double => double_joint(joint),
        BorderType::Thick => thick_joint(joint),
        BorderType::QuadrantInside => quad_inside_joint(joint),
        BorderType::QuadrantOutside => "X",
    };

    match joint.side {
        JointSide::Top => {
            if let Some(cell) = buf.cell_mut(Position::new(area.left() + n_pos, area.top())) {
                cell.set_symbol(sym);
            }
        }
        JointSide::Right => {
            if let Some(cell) = buf.cell_mut(Position::new(
                area.right().saturating_sub(1),
                area.top() + n_pos,
            )) {
                cell.set_symbol(sym);
            }
        }
        JointSide::Bottom => {
            if let Some(cell) = buf.cell_mut(Position::new(
                area.left() + n_pos,
                area.bottom().saturating_sub(1),
            )) {
                cell.set_symbol(sym);
            }
        }
        JointSide::Left => {
            if let Some(cell) = buf.cell_mut(Position::new(area.left(), area.top() + n_pos)) {
                cell.set_symbol(sym);
            }
        }
    }
}

fn plain_joint(joint: Joint) -> &'static str {
    use BorderType::*;
    use JointPos::*;
    use JointSide::*;

    if joint.scale == JointScale::Out {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┬",
            (Top, ProlongStart, Rounded) => "┬",
            (Top, ProlongStart, Double) => "┬",
            (Top, ProlongStart, Thick) => "┭",
            (Top, ProlongStart, QuadrantInside) => "┬",
            (Top, ProlongStart, QuadrantOutside) => "┬",
            (Top, Start, Plain) => "├",
            (Top, Start, Rounded) => "├",
            (Top, Start, Double) => "├",
            (Top, Start, Thick) => "┞",
            (Top, Start, QuadrantInside) => "├",
            (Top, Start, QuadrantOutside) => "├",
            (Top, Pos(_), Plain) => "┴",
            (Top, Pos(_), Rounded) => "┴",
            (Top, Pos(_), Double) => "╨",
            (Top, Pos(_), Thick) => "┸",
            (Top, Pos(_), QuadrantInside) => "┴",
            (Top, Pos(_), QuadrantOutside) => "┴",
            (Top, End, Plain) => "┤",
            (Top, End, Rounded) => "┤",
            (Top, End, Double) => "┤",
            (Top, End, Thick) => "┦",
            (Top, End, QuadrantInside) => "┤",
            (Top, End, QuadrantOutside) => "┤",
            (Top, ProlongEnd, Plain) => "┬",
            (Top, ProlongEnd, Rounded) => "┬",
            (Top, ProlongEnd, Double) => "┬",
            (Top, ProlongEnd, Thick) => "┮",
            (Top, ProlongEnd, QuadrantInside) => "┬",
            (Top, ProlongEnd, QuadrantOutside) => "┬",

            (Right, ProlongStart, Plain) => "┤",
            (Right, ProlongStart, Rounded) => "┤",
            (Right, ProlongStart, Double) => "┤",
            (Right, ProlongStart, Thick) => "┦",
            (Right, ProlongStart, QuadrantInside) => "┤",
            (Right, ProlongStart, QuadrantOutside) => "┤",
            (Right, Start, Plain) => "┬",
            (Right, Start, Rounded) => "┬",
            (Right, Start, Double) => "┬",
            (Right, Start, Thick) => "┮",
            (Right, Start, QuadrantInside) => "┬",
            (Right, Start, QuadrantOutside) => "┬",
            (Right, Pos(_), Plain) => "├",
            (Right, Pos(_), Rounded) => "├",
            (Right, Pos(_), Double) => "╞",
            (Right, Pos(_), Thick) => "┝",
            (Right, Pos(_), QuadrantInside) => "├",
            (Right, Pos(_), QuadrantOutside) => "├",
            (Right, End, Plain) => "┴",
            (Right, End, Rounded) => "┴",
            (Right, End, Double) => "┴",
            (Right, End, Thick) => "┶",
            (Right, End, QuadrantInside) => "┴",
            (Right, End, QuadrantOutside) => "┴",
            (Right, ProlongEnd, Plain) => "┤",
            (Right, ProlongEnd, Rounded) => "┤",
            (Right, ProlongEnd, Double) => "┤",
            (Right, ProlongEnd, Thick) => "┧",
            (Right, ProlongEnd, QuadrantInside) => "┤",
            (Right, ProlongEnd, QuadrantOutside) => "┤",

            (Bottom, ProlongStart, Plain) => "┴",
            (Bottom, ProlongStart, Rounded) => "┴",
            (Bottom, ProlongStart, Double) => "┴",
            (Bottom, ProlongStart, Thick) => "┵",
            (Bottom, ProlongStart, QuadrantInside) => "┴",
            (Bottom, ProlongStart, QuadrantOutside) => "┴",
            (Bottom, Start, Plain) => "├",
            (Bottom, Start, Rounded) => "├",
            (Bottom, Start, Double) => "├",
            (Bottom, Start, Thick) => "┟",
            (Bottom, Start, QuadrantInside) => "├",
            (Bottom, Start, QuadrantOutside) => "├",
            (Bottom, Pos(_), Plain) => "┬",
            (Bottom, Pos(_), Rounded) => "┬",
            (Bottom, Pos(_), Double) => "╥",
            (Bottom, Pos(_), Thick) => "┰",
            (Bottom, Pos(_), QuadrantInside) => "┬",
            (Bottom, Pos(_), QuadrantOutside) => "┬",
            (Bottom, End, Plain) => "┤",
            (Bottom, End, Rounded) => "┤",
            (Bottom, End, Double) => "┤",
            (Bottom, End, Thick) => "┧",
            (Bottom, End, QuadrantInside) => "┤",
            (Bottom, End, QuadrantOutside) => "┤",
            (Bottom, ProlongEnd, Plain) => "┴",
            (Bottom, ProlongEnd, Rounded) => "┴",
            (Bottom, ProlongEnd, Double) => "┴",
            (Bottom, ProlongEnd, Thick) => "┶",
            (Bottom, ProlongEnd, QuadrantInside) => "┴",
            (Bottom, ProlongEnd, QuadrantOutside) => "┴",

            (Left, ProlongStart, Plain) => "├",
            (Left, ProlongStart, Rounded) => "├",
            (Left, ProlongStart, Double) => "├",
            (Left, ProlongStart, Thick) => "┞",
            (Left, ProlongStart, QuadrantInside) => "├",
            (Left, ProlongStart, QuadrantOutside) => "├",
            (Left, Start, Plain) => "┬",
            (Left, Start, Rounded) => "┬",
            (Left, Start, Double) => "┬",
            (Left, Start, Thick) => "┭",
            (Left, Start, QuadrantInside) => "┬",
            (Left, Start, QuadrantOutside) => "┬",
            (Left, Pos(_), Plain) => "┤",
            (Left, Pos(_), Rounded) => "┤",
            (Left, Pos(_), Double) => "╡",
            (Left, Pos(_), Thick) => "┥",
            (Left, Pos(_), QuadrantInside) => "┤",
            (Left, Pos(_), QuadrantOutside) => "┤",
            (Left, End, Plain) => "┴",
            (Left, End, Rounded) => "┴",
            (Left, End, Double) => "┴",
            (Left, End, Thick) => "┵",
            (Left, End, QuadrantInside) => "┴",
            (Left, End, QuadrantOutside) => "┴",
            (Left, ProlongEnd, Plain) => "├",
            (Left, ProlongEnd, Rounded) => "├",
            (Left, ProlongEnd, Double) => "├",
            (Left, ProlongEnd, Thick) => "┟",
            (Left, ProlongEnd, QuadrantInside) => "├",
            (Left, ProlongEnd, QuadrantOutside) => "├",
        }
    } else if joint.scale == JointScale::In {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┌",
            (Top, ProlongStart, Rounded) => "┌",
            (Top, ProlongStart, Double) => "┌",
            (Top, ProlongStart, Thick) => "┌",
            (Top, ProlongStart, QuadrantInside) => "┌",
            (Top, ProlongStart, QuadrantOutside) => "┌",
            (Top, Start, Plain) => "┌",
            (Top, Start, Rounded) => "┌",
            (Top, Start, Double) => "┌",
            (Top, Start, Thick) => "┌",
            (Top, Start, QuadrantInside) => "┌",
            (Top, Start, QuadrantOutside) => "┌",
            (Top, Pos(_), Plain) => "┬",
            (Top, Pos(_), Rounded) => "┬",
            (Top, Pos(_), Double) => "╥",
            (Top, Pos(_), Thick) => "┰",
            (Top, Pos(_), QuadrantInside) => "┬",
            (Top, Pos(_), QuadrantOutside) => "┬",
            (Top, End, Plain) => "┐",
            (Top, End, Rounded) => "┐",
            (Top, End, Double) => "┐",
            (Top, End, Thick) => "┐",
            (Top, End, QuadrantInside) => "┐",
            (Top, End, QuadrantOutside) => "┐",
            (Top, ProlongEnd, Plain) => "┐",
            (Top, ProlongEnd, Rounded) => "┐",
            (Top, ProlongEnd, Double) => "┐",
            (Top, ProlongEnd, Thick) => "┐",
            (Top, ProlongEnd, QuadrantInside) => "┐",
            (Top, ProlongEnd, QuadrantOutside) => "┐",

            (Right, ProlongStart, Plain) => "┐",
            (Right, ProlongStart, Rounded) => "┐",
            (Right, ProlongStart, Double) => "┐",
            (Right, ProlongStart, Thick) => "┐",
            (Right, ProlongStart, QuadrantInside) => "┐",
            (Right, ProlongStart, QuadrantOutside) => "┐",
            (Right, Start, Plain) => "┐",
            (Right, Start, Rounded) => "┐",
            (Right, Start, Double) => "┐",
            (Right, Start, Thick) => "┐",
            (Right, Start, QuadrantInside) => "┐",
            (Right, Start, QuadrantOutside) => "┐",
            (Right, Pos(_), Plain) => "┤",
            (Right, Pos(_), Rounded) => "┤",
            (Right, Pos(_), Double) => "╡",
            (Right, Pos(_), Thick) => "┥",
            (Right, Pos(_), QuadrantInside) => "┤",
            (Right, Pos(_), QuadrantOutside) => "┤",
            (Right, End, Plain) => "┘",
            (Right, End, Rounded) => "┘",
            (Right, End, Double) => "┘",
            (Right, End, Thick) => "┘",
            (Right, End, QuadrantInside) => "┘",
            (Right, End, QuadrantOutside) => "┘",
            (Right, ProlongEnd, Plain) => "┘",
            (Right, ProlongEnd, Rounded) => "┘",
            (Right, ProlongEnd, Double) => "┘",
            (Right, ProlongEnd, Thick) => "┘",
            (Right, ProlongEnd, QuadrantInside) => "┘",
            (Right, ProlongEnd, QuadrantOutside) => "┘",

            (Bottom, ProlongStart, Plain) => "└",
            (Bottom, ProlongStart, Rounded) => "└",
            (Bottom, ProlongStart, Double) => "└",
            (Bottom, ProlongStart, Thick) => "└",
            (Bottom, ProlongStart, QuadrantInside) => "┘",
            (Bottom, ProlongStart, QuadrantOutside) => "┘",
            (Bottom, Start, Plain) => "└",
            (Bottom, Start, Rounded) => "└",
            (Bottom, Start, Double) => "└",
            (Bottom, Start, Thick) => "└",
            (Bottom, Start, QuadrantInside) => "┘",
            (Bottom, Start, QuadrantOutside) => "┘",
            (Bottom, Pos(_), Plain) => "┴",
            (Bottom, Pos(_), Rounded) => "┴",
            (Bottom, Pos(_), Double) => "╨",
            (Bottom, Pos(_), Thick) => "┸",
            (Bottom, Pos(_), QuadrantInside) => "┘",
            (Bottom, Pos(_), QuadrantOutside) => "┘",
            (Bottom, End, Plain) => "┘",
            (Bottom, End, Rounded) => "┘",
            (Bottom, End, Double) => "┘",
            (Bottom, End, Thick) => "┘",
            (Bottom, End, QuadrantInside) => "┘",
            (Bottom, End, QuadrantOutside) => "┘",
            (Bottom, ProlongEnd, Plain) => "┘",
            (Bottom, ProlongEnd, Rounded) => "┘",
            (Bottom, ProlongEnd, Double) => "┘",
            (Bottom, ProlongEnd, Thick) => "┘",
            (Bottom, ProlongEnd, QuadrantInside) => "┘",
            (Bottom, ProlongEnd, QuadrantOutside) => "┘",

            (Left, ProlongStart, Plain) => "┌",
            (Left, ProlongStart, Rounded) => "┌",
            (Left, ProlongStart, Double) => "┌",
            (Left, ProlongStart, Thick) => "┌",
            (Left, ProlongStart, QuadrantInside) => "┌",
            (Left, ProlongStart, QuadrantOutside) => "┌",
            (Left, Start, Plain) => "┌",
            (Left, Start, Rounded) => "┌",
            (Left, Start, Double) => "┌",
            (Left, Start, Thick) => "┌",
            (Left, Start, QuadrantInside) => "┌",
            (Left, Start, QuadrantOutside) => "┌",
            (Left, Pos(_), Plain) => "├",
            (Left, Pos(_), Rounded) => "├",
            (Left, Pos(_), Double) => "╞",
            (Left, Pos(_), Thick) => "┝",
            (Left, Pos(_), QuadrantInside) => "├",
            (Left, Pos(_), QuadrantOutside) => "├",
            (Left, End, Plain) => "└",
            (Left, End, Rounded) => "└",
            (Left, End, Double) => "└",
            (Left, End, Thick) => "└",
            (Left, End, QuadrantInside) => "└",
            (Left, End, QuadrantOutside) => "└",
            (Left, ProlongEnd, Plain) => "└",
            (Left, ProlongEnd, Rounded) => "└",
            (Left, ProlongEnd, Double) => "└",
            (Left, ProlongEnd, Thick) => "└",
            (Left, ProlongEnd, QuadrantInside) => "└",
            (Left, ProlongEnd, QuadrantOutside) => "└",
        }
    } else if joint.scale == JointScale::Through {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┌",
            (Top, ProlongStart, Rounded) => "┌",
            (Top, ProlongStart, Double) => "┌",
            (Top, ProlongStart, Thick) => "┌",
            (Top, ProlongStart, QuadrantInside) => "┌",
            (Top, ProlongStart, QuadrantOutside) => "┌",
            (Top, Start, Plain) => "┌",
            (Top, Start, Rounded) => "┌",
            (Top, Start, Double) => "┌",
            (Top, Start, Thick) => "┌",
            (Top, Start, QuadrantInside) => "┌",
            (Top, Start, QuadrantOutside) => "┌",
            (Top, Pos(_), Plain) => "┼",
            (Top, Pos(_), Rounded) => "┼",
            (Top, Pos(_), Double) => "╫",
            (Top, Pos(_), Thick) => "╂",
            (Top, Pos(_), QuadrantInside) => "┼",
            (Top, Pos(_), QuadrantOutside) => "┼",
            (Top, End, Plain) => "┐",
            (Top, End, Rounded) => "┐",
            (Top, End, Double) => "┐",
            (Top, End, Thick) => "┐",
            (Top, End, QuadrantInside) => "┐",
            (Top, End, QuadrantOutside) => "┐",
            (Top, ProlongEnd, Plain) => "┐",
            (Top, ProlongEnd, Rounded) => "┐",
            (Top, ProlongEnd, Double) => "┐",
            (Top, ProlongEnd, Thick) => "┐",
            (Top, ProlongEnd, QuadrantInside) => "┐",
            (Top, ProlongEnd, QuadrantOutside) => "┐",

            (Right, ProlongStart, Plain) => "┐",
            (Right, ProlongStart, Rounded) => "┐",
            (Right, ProlongStart, Double) => "┐",
            (Right, ProlongStart, Thick) => "┐",
            (Right, ProlongStart, QuadrantInside) => "┐",
            (Right, ProlongStart, QuadrantOutside) => "┐",
            (Right, Start, Plain) => "┐",
            (Right, Start, Rounded) => "┐",
            (Right, Start, Double) => "┐",
            (Right, Start, Thick) => "┐",
            (Right, Start, QuadrantInside) => "┐",
            (Right, Start, QuadrantOutside) => "┐",
            (Right, Pos(_), Plain) => "┼",
            (Right, Pos(_), Rounded) => "┼",
            (Right, Pos(_), Double) => "╪",
            (Right, Pos(_), Thick) => "┿",
            (Right, Pos(_), QuadrantInside) => "┼",
            (Right, Pos(_), QuadrantOutside) => "┼",
            (Right, End, Plain) => "┘",
            (Right, End, Rounded) => "┘",
            (Right, End, Double) => "┘",
            (Right, End, Thick) => "┘",
            (Right, End, QuadrantInside) => "┘",
            (Right, End, QuadrantOutside) => "┘",
            (Right, ProlongEnd, Plain) => "┘",
            (Right, ProlongEnd, Rounded) => "┘",
            (Right, ProlongEnd, Double) => "┘",
            (Right, ProlongEnd, Thick) => "┘",
            (Right, ProlongEnd, QuadrantInside) => "┘",
            (Right, ProlongEnd, QuadrantOutside) => "┘",

            (Bottom, ProlongStart, Plain) => "└",
            (Bottom, ProlongStart, Rounded) => "└",
            (Bottom, ProlongStart, Double) => "└",
            (Bottom, ProlongStart, Thick) => "└",
            (Bottom, ProlongStart, QuadrantInside) => "└",
            (Bottom, ProlongStart, QuadrantOutside) => "└",
            (Bottom, Start, Plain) => "└",
            (Bottom, Start, Rounded) => "└",
            (Bottom, Start, Double) => "└",
            (Bottom, Start, Thick) => "└",
            (Bottom, Start, QuadrantInside) => "└",
            (Bottom, Start, QuadrantOutside) => "└",
            (Bottom, Pos(_), Plain) => "┼",
            (Bottom, Pos(_), Rounded) => "┼",
            (Bottom, Pos(_), Double) => "╫",
            (Bottom, Pos(_), Thick) => "╂",
            (Bottom, Pos(_), QuadrantInside) => "┼",
            (Bottom, Pos(_), QuadrantOutside) => "┼",
            (Bottom, End, Plain) => "┘",
            (Bottom, End, Rounded) => "┘",
            (Bottom, End, Double) => "┘",
            (Bottom, End, Thick) => "┘",
            (Bottom, End, QuadrantInside) => "┘",
            (Bottom, End, QuadrantOutside) => "┘",
            (Bottom, ProlongEnd, Plain) => "┘",
            (Bottom, ProlongEnd, Rounded) => "┘",
            (Bottom, ProlongEnd, Double) => "┘",
            (Bottom, ProlongEnd, Thick) => "┘",
            (Bottom, ProlongEnd, QuadrantInside) => "┘",
            (Bottom, ProlongEnd, QuadrantOutside) => "┘",

            (Left, ProlongStart, Plain) => "┌",
            (Left, ProlongStart, Rounded) => "┌",
            (Left, ProlongStart, Double) => "┌",
            (Left, ProlongStart, Thick) => "┌",
            (Left, ProlongStart, QuadrantInside) => "┌",
            (Left, ProlongStart, QuadrantOutside) => "┌",
            (Left, Start, Plain) => "┌",
            (Left, Start, Rounded) => "┌",
            (Left, Start, Double) => "┌",
            (Left, Start, Thick) => "┌",
            (Left, Start, QuadrantInside) => "┌",
            (Left, Start, QuadrantOutside) => "┌",
            (Left, Pos(_), Plain) => "┼",
            (Left, Pos(_), Rounded) => "┼",
            (Left, Pos(_), Double) => "╪",
            (Left, Pos(_), Thick) => "┿",
            (Left, Pos(_), QuadrantInside) => "┼",
            (Left, Pos(_), QuadrantOutside) => "┼",
            (Left, End, Plain) => "└",
            (Left, End, Rounded) => "└",
            (Left, End, Double) => "└",
            (Left, End, Thick) => "└",
            (Left, End, QuadrantInside) => "└",
            (Left, End, QuadrantOutside) => "└",
            (Left, ProlongEnd, Plain) => "└",
            (Left, ProlongEnd, Rounded) => "└",
            (Left, ProlongEnd, Double) => "└",
            (Left, ProlongEnd, Thick) => "└",
            (Left, ProlongEnd, QuadrantInside) => "└",
            (Left, ProlongEnd, QuadrantOutside) => "└",
        }
    } else if let JointScale::Manual(cc) = joint.scale {
        cc
    } else {
        unreachable!()
    }
}

fn double_joint(joint: Joint) -> &'static str {
    use BorderType::*;
    use JointPos::*;
    use JointSide::*;

    if joint.scale == JointScale::Out {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "╦",
            (Top, ProlongStart, Rounded) => "╦",
            (Top, ProlongStart, Double) => "╦",
            (Top, ProlongStart, Thick) => "╦",
            (Top, ProlongStart, QuadrantInside) => "╦",
            (Top, ProlongStart, QuadrantOutside) => "╦",
            (Top, Start, Plain) => "╠",
            (Top, Start, Rounded) => "╠",
            (Top, Start, Double) => "╠",
            (Top, Start, Thick) => "╠",
            (Top, Start, QuadrantInside) => "╠",
            (Top, Start, QuadrantOutside) => "╠",
            (Top, Pos(_), Plain) => "╧",
            (Top, Pos(_), Rounded) => "╧",
            (Top, Pos(_), Double) => "╩",
            (Top, Pos(_), Thick) => "╩",
            (Top, Pos(_), QuadrantInside) => "╩",
            (Top, Pos(_), QuadrantOutside) => "╩",
            (Top, End, Plain) => "╣",
            (Top, End, Rounded) => "╣",
            (Top, End, Double) => "╣",
            (Top, End, Thick) => "╣",
            (Top, End, QuadrantInside) => "╣",
            (Top, End, QuadrantOutside) => "╣",
            (Top, ProlongEnd, Plain) => "╦",
            (Top, ProlongEnd, Rounded) => "╦",
            (Top, ProlongEnd, Double) => "╦",
            (Top, ProlongEnd, Thick) => "╦",
            (Top, ProlongEnd, QuadrantInside) => "╦",
            (Top, ProlongEnd, QuadrantOutside) => "╦",

            (Right, ProlongStart, Plain) => "╣",
            (Right, ProlongStart, Rounded) => "╣",
            (Right, ProlongStart, Double) => "╣",
            (Right, ProlongStart, Thick) => "╣",
            (Right, ProlongStart, QuadrantInside) => "╣",
            (Right, ProlongStart, QuadrantOutside) => "╣",
            (Right, Start, Plain) => "╦",
            (Right, Start, Rounded) => "╦",
            (Right, Start, Double) => "╦",
            (Right, Start, Thick) => "╦",
            (Right, Start, QuadrantInside) => "╦",
            (Right, Start, QuadrantOutside) => "╦",
            (Right, Pos(_), Plain) => "╟",
            (Right, Pos(_), Rounded) => "╟",
            (Right, Pos(_), Double) => "╠",
            (Right, Pos(_), Thick) => "╠",
            (Right, Pos(_), QuadrantInside) => "╟",
            (Right, Pos(_), QuadrantOutside) => "╟",
            (Right, End, Plain) => "╩",
            (Right, End, Rounded) => "╩",
            (Right, End, Double) => "╩",
            (Right, End, Thick) => "╩",
            (Right, End, QuadrantInside) => "╩",
            (Right, End, QuadrantOutside) => "╩",
            (Right, ProlongEnd, Plain) => "╣",
            (Right, ProlongEnd, Rounded) => "╣",
            (Right, ProlongEnd, Double) => "╣",
            (Right, ProlongEnd, Thick) => "╣",
            (Right, ProlongEnd, QuadrantInside) => "╣",
            (Right, ProlongEnd, QuadrantOutside) => "╣",

            (Bottom, ProlongStart, Plain) => "╩",
            (Bottom, ProlongStart, Rounded) => "╩",
            (Bottom, ProlongStart, Double) => "╩",
            (Bottom, ProlongStart, Thick) => "╩",
            (Bottom, ProlongStart, QuadrantInside) => "╩",
            (Bottom, ProlongStart, QuadrantOutside) => "╩",
            (Bottom, Start, Plain) => "╠",
            (Bottom, Start, Rounded) => "╠",
            (Bottom, Start, Double) => "╠",
            (Bottom, Start, Thick) => "╠",
            (Bottom, Start, QuadrantInside) => "╠",
            (Bottom, Start, QuadrantOutside) => "╠",
            (Bottom, Pos(_), Plain) => "╤",
            (Bottom, Pos(_), Rounded) => "╤",
            (Bottom, Pos(_), Double) => "╦",
            (Bottom, Pos(_), Thick) => "╦",
            (Bottom, Pos(_), QuadrantInside) => "╦",
            (Bottom, Pos(_), QuadrantOutside) => "╦",
            (Bottom, End, Plain) => "╣",
            (Bottom, End, Rounded) => "╣",
            (Bottom, End, Double) => "╣",
            (Bottom, End, Thick) => "╣",
            (Bottom, End, QuadrantInside) => "╣",
            (Bottom, End, QuadrantOutside) => "╣",
            (Bottom, ProlongEnd, Plain) => "╩",
            (Bottom, ProlongEnd, Rounded) => "╩",
            (Bottom, ProlongEnd, Double) => "╩",
            (Bottom, ProlongEnd, Thick) => "╩",
            (Bottom, ProlongEnd, QuadrantInside) => "╩",
            (Bottom, ProlongEnd, QuadrantOutside) => "╩",

            (Left, ProlongStart, Plain) => "╠",
            (Left, ProlongStart, Rounded) => "╠",
            (Left, ProlongStart, Double) => "╠",
            (Left, ProlongStart, Thick) => "╠",
            (Left, ProlongStart, QuadrantInside) => "╠",
            (Left, ProlongStart, QuadrantOutside) => "╠",
            (Left, Start, Plain) => "╦",
            (Left, Start, Rounded) => "╦",
            (Left, Start, Double) => "╦",
            (Left, Start, Thick) => "╦",
            (Left, Start, QuadrantInside) => "╦",
            (Left, Start, QuadrantOutside) => "╦",
            (Left, Pos(_), Plain) => "╢",
            (Left, Pos(_), Rounded) => "╢",
            (Left, Pos(_), Double) => "╣",
            (Left, Pos(_), Thick) => "╣",
            (Left, Pos(_), QuadrantInside) => "╣",
            (Left, Pos(_), QuadrantOutside) => "╣",
            (Left, End, Plain) => "╩",
            (Left, End, Rounded) => "╩",
            (Left, End, Double) => "╩",
            (Left, End, Thick) => "╩",
            (Left, End, QuadrantInside) => "╩",
            (Left, End, QuadrantOutside) => "╩",
            (Left, ProlongEnd, Plain) => "╠",
            (Left, ProlongEnd, Rounded) => "╠",
            (Left, ProlongEnd, Double) => "╠",
            (Left, ProlongEnd, Thick) => "╠",
            (Left, ProlongEnd, QuadrantInside) => "╠",
            (Left, ProlongEnd, QuadrantOutside) => "╠",
        }
    } else if joint.scale == JointScale::In {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "╔",
            (Top, ProlongStart, Rounded) => "╔",
            (Top, ProlongStart, Double) => "╔",
            (Top, ProlongStart, Thick) => "╔",
            (Top, ProlongStart, QuadrantInside) => "╔",
            (Top, ProlongStart, QuadrantOutside) => "╔",
            (Top, Start, Plain) => "╔",
            (Top, Start, Rounded) => "╔",
            (Top, Start, Double) => "╔",
            (Top, Start, Thick) => "╔",
            (Top, Start, QuadrantInside) => "╔",
            (Top, Start, QuadrantOutside) => "╔",
            (Top, Pos(_), Plain) => "╤",
            (Top, Pos(_), Rounded) => "╤",
            (Top, Pos(_), Double) => "╦",
            (Top, Pos(_), Thick) => "╦",
            (Top, Pos(_), QuadrantInside) => "╦",
            (Top, Pos(_), QuadrantOutside) => "╦",
            (Top, End, Plain) => "╗",
            (Top, End, Rounded) => "╗",
            (Top, End, Double) => "╗",
            (Top, End, Thick) => "╗",
            (Top, End, QuadrantInside) => "╗",
            (Top, End, QuadrantOutside) => "╗",
            (Top, ProlongEnd, Plain) => "╗",
            (Top, ProlongEnd, Rounded) => "╗",
            (Top, ProlongEnd, Double) => "╗",
            (Top, ProlongEnd, Thick) => "╗",
            (Top, ProlongEnd, QuadrantInside) => "╗",
            (Top, ProlongEnd, QuadrantOutside) => "╗",

            (Right, ProlongStart, Plain) => "╗",
            (Right, ProlongStart, Rounded) => "╗",
            (Right, ProlongStart, Double) => "╗",
            (Right, ProlongStart, Thick) => "╗",
            (Right, ProlongStart, QuadrantInside) => "╗",
            (Right, ProlongStart, QuadrantOutside) => "╗",
            (Right, Start, Plain) => "╗",
            (Right, Start, Rounded) => "╗",
            (Right, Start, Double) => "╗",
            (Right, Start, Thick) => "╗",
            (Right, Start, QuadrantInside) => "╗",
            (Right, Start, QuadrantOutside) => "╗",
            (Right, Pos(_), Plain) => "╢",
            (Right, Pos(_), Rounded) => "╢",
            (Right, Pos(_), Double) => "╣",
            (Right, Pos(_), Thick) => "╣",
            (Right, Pos(_), QuadrantInside) => "╣",
            (Right, Pos(_), QuadrantOutside) => "╣",
            (Right, End, Plain) => "╝",
            (Right, End, Rounded) => "╝",
            (Right, End, Double) => "╝",
            (Right, End, Thick) => "╝",
            (Right, End, QuadrantInside) => "╝",
            (Right, End, QuadrantOutside) => "╝",
            (Right, ProlongEnd, Plain) => "╝",
            (Right, ProlongEnd, Rounded) => "╝",
            (Right, ProlongEnd, Double) => "╝",
            (Right, ProlongEnd, Thick) => "╝",
            (Right, ProlongEnd, QuadrantInside) => "╝",
            (Right, ProlongEnd, QuadrantOutside) => "╝",

            (Bottom, ProlongStart, Plain) => "╚",
            (Bottom, ProlongStart, Rounded) => "╚",
            (Bottom, ProlongStart, Double) => "╚",
            (Bottom, ProlongStart, Thick) => "╚",
            (Bottom, ProlongStart, QuadrantInside) => "╚",
            (Bottom, ProlongStart, QuadrantOutside) => "╚",
            (Bottom, Start, Plain) => "╚",
            (Bottom, Start, Rounded) => "╚",
            (Bottom, Start, Double) => "╚",
            (Bottom, Start, Thick) => "╚",
            (Bottom, Start, QuadrantInside) => "╚",
            (Bottom, Start, QuadrantOutside) => "╚",
            (Bottom, Pos(_), Plain) => "╧",
            (Bottom, Pos(_), Rounded) => "╧",
            (Bottom, Pos(_), Double) => "╩",
            (Bottom, Pos(_), Thick) => "╩",
            (Bottom, Pos(_), QuadrantInside) => "╩",
            (Bottom, Pos(_), QuadrantOutside) => "╩",
            (Bottom, End, Plain) => "╝",
            (Bottom, End, Rounded) => "╝",
            (Bottom, End, Double) => "╝",
            (Bottom, End, Thick) => "╝",
            (Bottom, End, QuadrantInside) => "╝",
            (Bottom, End, QuadrantOutside) => "╝",
            (Bottom, ProlongEnd, Plain) => "╝",
            (Bottom, ProlongEnd, Rounded) => "╝",
            (Bottom, ProlongEnd, Double) => "╝",
            (Bottom, ProlongEnd, Thick) => "╝",
            (Bottom, ProlongEnd, QuadrantInside) => "╝",
            (Bottom, ProlongEnd, QuadrantOutside) => "╝",

            (Left, ProlongStart, Plain) => "╔",
            (Left, ProlongStart, Rounded) => "╔",
            (Left, ProlongStart, Double) => "╔",
            (Left, ProlongStart, Thick) => "╔",
            (Left, ProlongStart, QuadrantInside) => "╔",
            (Left, ProlongStart, QuadrantOutside) => "╔",
            (Left, Start, Plain) => "╔",
            (Left, Start, Rounded) => "╔",
            (Left, Start, Double) => "╔",
            (Left, Start, Thick) => "╔",
            (Left, Start, QuadrantInside) => "╔",
            (Left, Start, QuadrantOutside) => "╔",
            (Left, Pos(_), Plain) => "╟",
            (Left, Pos(_), Rounded) => "╟",
            (Left, Pos(_), Double) => "╠",
            (Left, Pos(_), Thick) => "╠",
            (Left, Pos(_), QuadrantInside) => "╠",
            (Left, Pos(_), QuadrantOutside) => "╠",
            (Left, End, Plain) => "╚",
            (Left, End, Rounded) => "╚",
            (Left, End, Double) => "╚",
            (Left, End, Thick) => "╚",
            (Left, End, QuadrantInside) => "╚",
            (Left, End, QuadrantOutside) => "╚",
            (Left, ProlongEnd, Plain) => "╚",
            (Left, ProlongEnd, Rounded) => "╚",
            (Left, ProlongEnd, Double) => "╚",
            (Left, ProlongEnd, Thick) => "╚",
            (Left, ProlongEnd, QuadrantInside) => "╚",
            (Left, ProlongEnd, QuadrantOutside) => "╚",
        }
    } else if joint.scale == JointScale::Through {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "╔",
            (Top, ProlongStart, Rounded) => "╔",
            (Top, ProlongStart, Double) => "╔",
            (Top, ProlongStart, Thick) => "╔",
            (Top, ProlongStart, QuadrantInside) => "╔",
            (Top, ProlongStart, QuadrantOutside) => "╔",
            (Top, Start, Plain) => "╔",
            (Top, Start, Rounded) => "╔",
            (Top, Start, Double) => "╔",
            (Top, Start, Thick) => "╔",
            (Top, Start, QuadrantInside) => "╔",
            (Top, Start, QuadrantOutside) => "╔",
            (Top, Pos(_), Plain) => "╪",
            (Top, Pos(_), Rounded) => "╪",
            (Top, Pos(_), Double) => "╬",
            (Top, Pos(_), Thick) => "╬",
            (Top, Pos(_), QuadrantInside) => "╬",
            (Top, Pos(_), QuadrantOutside) => "╬",
            (Top, End, Plain) => "╗",
            (Top, End, Rounded) => "╗",
            (Top, End, Double) => "╗",
            (Top, End, Thick) => "╗",
            (Top, End, QuadrantInside) => "╗",
            (Top, End, QuadrantOutside) => "╗",
            (Top, ProlongEnd, Plain) => "╗",
            (Top, ProlongEnd, Rounded) => "╗",
            (Top, ProlongEnd, Double) => "╗",
            (Top, ProlongEnd, Thick) => "╗",
            (Top, ProlongEnd, QuadrantInside) => "╗",
            (Top, ProlongEnd, QuadrantOutside) => "╗",

            (Right, ProlongStart, Plain) => "╗",
            (Right, ProlongStart, Rounded) => "╗",
            (Right, ProlongStart, Double) => "╗",
            (Right, ProlongStart, Thick) => "╗",
            (Right, ProlongStart, QuadrantInside) => "╗",
            (Right, ProlongStart, QuadrantOutside) => "╗",
            (Right, Start, Plain) => "╗",
            (Right, Start, Rounded) => "╗",
            (Right, Start, Double) => "╗",
            (Right, Start, Thick) => "╗",
            (Right, Start, QuadrantInside) => "╗",
            (Right, Start, QuadrantOutside) => "╗",
            (Right, Pos(_), Plain) => "╫",
            (Right, Pos(_), Rounded) => "╫",
            (Right, Pos(_), Double) => "╬",
            (Right, Pos(_), Thick) => "╬",
            (Right, Pos(_), QuadrantInside) => "╬",
            (Right, Pos(_), QuadrantOutside) => "╬",
            (Right, End, Plain) => "╝",
            (Right, End, Rounded) => "╝",
            (Right, End, Double) => "╝",
            (Right, End, Thick) => "╝",
            (Right, End, QuadrantInside) => "╝",
            (Right, End, QuadrantOutside) => "╝",
            (Right, ProlongEnd, Plain) => "╝",
            (Right, ProlongEnd, Rounded) => "╝",
            (Right, ProlongEnd, Double) => "╝",
            (Right, ProlongEnd, Thick) => "╝",
            (Right, ProlongEnd, QuadrantInside) => "╝",
            (Right, ProlongEnd, QuadrantOutside) => "╝",

            (Bottom, ProlongStart, Plain) => "╚",
            (Bottom, ProlongStart, Rounded) => "╚",
            (Bottom, ProlongStart, Double) => "╚",
            (Bottom, ProlongStart, Thick) => "╚",
            (Bottom, ProlongStart, QuadrantInside) => "╚",
            (Bottom, ProlongStart, QuadrantOutside) => "╚",
            (Bottom, Start, Plain) => "╚",
            (Bottom, Start, Rounded) => "╚",
            (Bottom, Start, Double) => "╚",
            (Bottom, Start, Thick) => "╚",
            (Bottom, Start, QuadrantInside) => "╚",
            (Bottom, Start, QuadrantOutside) => "╚",
            (Bottom, Pos(_), Plain) => "╪",
            (Bottom, Pos(_), Rounded) => "╪",
            (Bottom, Pos(_), Double) => "╬",
            (Bottom, Pos(_), Thick) => "╬",
            (Bottom, Pos(_), QuadrantInside) => "╬",
            (Bottom, Pos(_), QuadrantOutside) => "╬",
            (Bottom, End, Plain) => "╝",
            (Bottom, End, Rounded) => "╝",
            (Bottom, End, Double) => "╝",
            (Bottom, End, Thick) => "╝",
            (Bottom, End, QuadrantInside) => "╝",
            (Bottom, End, QuadrantOutside) => "╝",
            (Bottom, ProlongEnd, Plain) => "╝",
            (Bottom, ProlongEnd, Rounded) => "╝",
            (Bottom, ProlongEnd, Double) => "╝",
            (Bottom, ProlongEnd, Thick) => "╝",
            (Bottom, ProlongEnd, QuadrantInside) => "╝",
            (Bottom, ProlongEnd, QuadrantOutside) => "╝",

            (Left, ProlongStart, Plain) => "╔",
            (Left, ProlongStart, Rounded) => "╔",
            (Left, ProlongStart, Double) => "╔",
            (Left, ProlongStart, Thick) => "╔",
            (Left, ProlongStart, QuadrantInside) => "╔",
            (Left, ProlongStart, QuadrantOutside) => "╔",
            (Left, Start, Plain) => "╔",
            (Left, Start, Rounded) => "╔",
            (Left, Start, Double) => "╔",
            (Left, Start, Thick) => "╔",
            (Left, Start, QuadrantInside) => "╔",
            (Left, Start, QuadrantOutside) => "╔",
            (Left, Pos(_), Plain) => "╫",
            (Left, Pos(_), Rounded) => "╫",
            (Left, Pos(_), Double) => "╬",
            (Left, Pos(_), Thick) => "╬",
            (Left, Pos(_), QuadrantInside) => "╬",
            (Left, Pos(_), QuadrantOutside) => "╬",
            (Left, End, Plain) => "╚",
            (Left, End, Rounded) => "╚",
            (Left, End, Double) => "╚",
            (Left, End, Thick) => "╚",
            (Left, End, QuadrantInside) => "╚",
            (Left, End, QuadrantOutside) => "╚",
            (Left, ProlongEnd, Plain) => "╚",
            (Left, ProlongEnd, Rounded) => "╚",
            (Left, ProlongEnd, Double) => "╚",
            (Left, ProlongEnd, Thick) => "╚",
            (Left, ProlongEnd, QuadrantInside) => "╚",
            (Left, ProlongEnd, QuadrantOutside) => "╚",
        }
    } else if let JointScale::Manual(cc) = joint.scale {
        cc
    } else {
        unreachable!()
    }
}

fn thick_joint(joint: Joint) -> &'static str {
    use BorderType::*;
    use JointPos::*;
    use JointSide::*;

    if joint.scale == JointScale::Out {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┲",
            (Top, ProlongStart, Rounded) => "┲",
            (Top, ProlongStart, Double) => "┳",
            (Top, ProlongStart, Thick) => "┳",
            (Top, ProlongStart, QuadrantInside) => "┳",
            (Top, ProlongStart, QuadrantOutside) => "┳",
            (Top, Start, Plain) => "┢",
            (Top, Start, Rounded) => "┢",
            (Top, Start, Double) => "┣",
            (Top, Start, Thick) => "┣",
            (Top, Start, QuadrantInside) => "┣",
            (Top, Start, QuadrantOutside) => "┣",
            (Top, Pos(_), Plain) => "┷",
            (Top, Pos(_), Rounded) => "┷",
            (Top, Pos(_), Double) => "┻",
            (Top, Pos(_), Thick) => "┻",
            (Top, Pos(_), QuadrantInside) => "┻",
            (Top, Pos(_), QuadrantOutside) => "┻",
            (Top, End, Plain) => "┪",
            (Top, End, Rounded) => "┪",
            (Top, End, Double) => "┫",
            (Top, End, Thick) => "┫",
            (Top, End, QuadrantInside) => "┫",
            (Top, End, QuadrantOutside) => "┫",
            (Top, ProlongEnd, Plain) => "┱",
            (Top, ProlongEnd, Rounded) => "┱",
            (Top, ProlongEnd, Double) => "┳",
            (Top, ProlongEnd, Thick) => "┳",
            (Top, ProlongEnd, QuadrantInside) => "┳",
            (Top, ProlongEnd, QuadrantOutside) => "┳",

            (Right, ProlongStart, Plain) => "┪",
            (Right, ProlongStart, Rounded) => "┪",
            (Right, ProlongStart, Double) => "┫",
            (Right, ProlongStart, Thick) => "┫",
            (Right, ProlongStart, QuadrantInside) => "┫",
            (Right, ProlongStart, QuadrantOutside) => "┫",
            (Right, Start, Plain) => "┱",
            (Right, Start, Rounded) => "┱",
            (Right, Start, Double) => "┳",
            (Right, Start, Thick) => "┳",
            (Right, Start, QuadrantInside) => "┳",
            (Right, Start, QuadrantOutside) => "┳",
            (Right, Pos(_), Plain) => "┠",
            (Right, Pos(_), Rounded) => "┠",
            (Right, Pos(_), Double) => "┣",
            (Right, Pos(_), Thick) => "┣",
            (Right, Pos(_), QuadrantInside) => "┣",
            (Right, Pos(_), QuadrantOutside) => "┣",
            (Right, End, Plain) => "┹",
            (Right, End, Rounded) => "┹",
            (Right, End, Double) => "┻",
            (Right, End, Thick) => "┻",
            (Right, End, QuadrantInside) => "┻",
            (Right, End, QuadrantOutside) => "┻",
            (Right, ProlongEnd, Plain) => "┩",
            (Right, ProlongEnd, Rounded) => "┩",
            (Right, ProlongEnd, Double) => "┫",
            (Right, ProlongEnd, Thick) => "┫",
            (Right, ProlongEnd, QuadrantInside) => "┫",
            (Right, ProlongEnd, QuadrantOutside) => "┫",

            (Bottom, ProlongStart, Plain) => "┺",
            (Bottom, ProlongStart, Rounded) => "┺",
            (Bottom, ProlongStart, Double) => "┻",
            (Bottom, ProlongStart, Thick) => "┻",
            (Bottom, ProlongStart, QuadrantInside) => "┻",
            (Bottom, ProlongStart, QuadrantOutside) => "┻",
            (Bottom, Start, Plain) => "┡",
            (Bottom, Start, Rounded) => "┡",
            (Bottom, Start, Double) => "┣",
            (Bottom, Start, Thick) => "┣",
            (Bottom, Start, QuadrantInside) => "┣",
            (Bottom, Start, QuadrantOutside) => "┣",
            (Bottom, Pos(_), Plain) => "┯",
            (Bottom, Pos(_), Rounded) => "┯",
            (Bottom, Pos(_), Double) => "┳",
            (Bottom, Pos(_), Thick) => "┳",
            (Bottom, Pos(_), QuadrantInside) => "┳",
            (Bottom, Pos(_), QuadrantOutside) => "┳",
            (Bottom, End, Plain) => "┩",
            (Bottom, End, Rounded) => "┩",
            (Bottom, End, Double) => "┫",
            (Bottom, End, Thick) => "┫",
            (Bottom, End, QuadrantInside) => "┫",
            (Bottom, End, QuadrantOutside) => "┫",
            (Bottom, ProlongEnd, Plain) => "┹",
            (Bottom, ProlongEnd, Rounded) => "┹",
            (Bottom, ProlongEnd, Double) => "┻",
            (Bottom, ProlongEnd, Thick) => "┻",
            (Bottom, ProlongEnd, QuadrantInside) => "┻",
            (Bottom, ProlongEnd, QuadrantOutside) => "┻",

            (Left, ProlongStart, Plain) => "┢",
            (Left, ProlongStart, Rounded) => "┢",
            (Left, ProlongStart, Double) => "┣",
            (Left, ProlongStart, Thick) => "┣",
            (Left, ProlongStart, QuadrantInside) => "┣",
            (Left, ProlongStart, QuadrantOutside) => "┣",
            (Left, Start, Plain) => "┲",
            (Left, Start, Rounded) => "┲",
            (Left, Start, Double) => "┳",
            (Left, Start, Thick) => "┳",
            (Left, Start, QuadrantInside) => "┳",
            (Left, Start, QuadrantOutside) => "┳",
            (Left, Pos(_), Plain) => "┨",
            (Left, Pos(_), Rounded) => "┨",
            (Left, Pos(_), Double) => "┫",
            (Left, Pos(_), Thick) => "┫",
            (Left, Pos(_), QuadrantInside) => "┫",
            (Left, Pos(_), QuadrantOutside) => "┫",
            (Left, End, Plain) => "┺",
            (Left, End, Rounded) => "┺",
            (Left, End, Double) => "┻",
            (Left, End, Thick) => "┻",
            (Left, End, QuadrantInside) => "┻",
            (Left, End, QuadrantOutside) => "┻",
            (Left, ProlongEnd, Plain) => "┡",
            (Left, ProlongEnd, Rounded) => "┡",
            (Left, ProlongEnd, Double) => "┣",
            (Left, ProlongEnd, Thick) => "┣",
            (Left, ProlongEnd, QuadrantInside) => "┣",
            (Left, ProlongEnd, QuadrantOutside) => "┣",
        }
    } else if joint.scale == JointScale::In {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┏",
            (Top, ProlongStart, Rounded) => "┏",
            (Top, ProlongStart, Double) => "┏",
            (Top, ProlongStart, Thick) => "┏",
            (Top, ProlongStart, QuadrantInside) => "┏",
            (Top, ProlongStart, QuadrantOutside) => "┏",
            (Top, Start, Plain) => "┏",
            (Top, Start, Rounded) => "┏",
            (Top, Start, Double) => "┏",
            (Top, Start, Thick) => "┏",
            (Top, Start, QuadrantInside) => "┏",
            (Top, Start, QuadrantOutside) => "┏",
            (Top, Pos(_), Plain) => "┯",
            (Top, Pos(_), Rounded) => "┯",
            (Top, Pos(_), Double) => "┳",
            (Top, Pos(_), Thick) => "┳",
            (Top, Pos(_), QuadrantInside) => "┳",
            (Top, Pos(_), QuadrantOutside) => "┳",
            (Top, End, Plain) => "┓",
            (Top, End, Rounded) => "┓",
            (Top, End, Double) => "┓",
            (Top, End, Thick) => "┓",
            (Top, End, QuadrantInside) => "┓",
            (Top, End, QuadrantOutside) => "┓",
            (Top, ProlongEnd, Plain) => "┓",
            (Top, ProlongEnd, Rounded) => "┓",
            (Top, ProlongEnd, Double) => "┓",
            (Top, ProlongEnd, Thick) => "┓",
            (Top, ProlongEnd, QuadrantInside) => "┓",
            (Top, ProlongEnd, QuadrantOutside) => "┓",

            (Right, ProlongStart, Plain) => "┓",
            (Right, ProlongStart, Rounded) => "┓",
            (Right, ProlongStart, Double) => "┓",
            (Right, ProlongStart, Thick) => "┓",
            (Right, ProlongStart, QuadrantInside) => "┓",
            (Right, ProlongStart, QuadrantOutside) => "┓",
            (Right, Start, Plain) => "┓",
            (Right, Start, Rounded) => "┓",
            (Right, Start, Double) => "┓",
            (Right, Start, Thick) => "┓",
            (Right, Start, QuadrantInside) => "┓",
            (Right, Start, QuadrantOutside) => "┓",
            (Right, Pos(_), Plain) => "┨",
            (Right, Pos(_), Rounded) => "┨",
            (Right, Pos(_), Double) => "┫",
            (Right, Pos(_), Thick) => "┫",
            (Right, Pos(_), QuadrantInside) => "┫",
            (Right, Pos(_), QuadrantOutside) => "┫",
            (Right, End, Plain) => "┛",
            (Right, End, Rounded) => "┛",
            (Right, End, Double) => "┛",
            (Right, End, Thick) => "┛",
            (Right, End, QuadrantInside) => "┛",
            (Right, End, QuadrantOutside) => "┛",
            (Right, ProlongEnd, Plain) => "┛",
            (Right, ProlongEnd, Rounded) => "┛",
            (Right, ProlongEnd, Double) => "┛",
            (Right, ProlongEnd, Thick) => "┛",
            (Right, ProlongEnd, QuadrantInside) => "┛",
            (Right, ProlongEnd, QuadrantOutside) => "┛",

            (Bottom, ProlongStart, Plain) => "┗",
            (Bottom, ProlongStart, Rounded) => "┗",
            (Bottom, ProlongStart, Double) => "┗",
            (Bottom, ProlongStart, Thick) => "┗",
            (Bottom, ProlongStart, QuadrantInside) => "┗",
            (Bottom, ProlongStart, QuadrantOutside) => "┗",
            (Bottom, Start, Plain) => "┗",
            (Bottom, Start, Rounded) => "┗",
            (Bottom, Start, Double) => "┗",
            (Bottom, Start, Thick) => "┗",
            (Bottom, Start, QuadrantInside) => "┗",
            (Bottom, Start, QuadrantOutside) => "┗",
            (Bottom, Pos(_), Plain) => "┷",
            (Bottom, Pos(_), Rounded) => "┷",
            (Bottom, Pos(_), Double) => "┻",
            (Bottom, Pos(_), Thick) => "┻",
            (Bottom, Pos(_), QuadrantInside) => "┻",
            (Bottom, Pos(_), QuadrantOutside) => "┻",
            (Bottom, End, Plain) => "┛",
            (Bottom, End, Rounded) => "┛",
            (Bottom, End, Double) => "┛",
            (Bottom, End, Thick) => "┛",
            (Bottom, End, QuadrantInside) => "┛",
            (Bottom, End, QuadrantOutside) => "┛",
            (Bottom, ProlongEnd, Plain) => "┛",
            (Bottom, ProlongEnd, Rounded) => "┛",
            (Bottom, ProlongEnd, Double) => "┛",
            (Bottom, ProlongEnd, Thick) => "┛",
            (Bottom, ProlongEnd, QuadrantInside) => "┛",
            (Bottom, ProlongEnd, QuadrantOutside) => "┛",

            (Left, ProlongStart, Plain) => "┏",
            (Left, ProlongStart, Rounded) => "┏",
            (Left, ProlongStart, Double) => "┏",
            (Left, ProlongStart, Thick) => "┏",
            (Left, ProlongStart, QuadrantInside) => "┏",
            (Left, ProlongStart, QuadrantOutside) => "┏",
            (Left, Start, Plain) => "┏",
            (Left, Start, Rounded) => "┏",
            (Left, Start, Double) => "┏",
            (Left, Start, Thick) => "┏",
            (Left, Start, QuadrantInside) => "┏",
            (Left, Start, QuadrantOutside) => "┏",
            (Left, Pos(_), Plain) => "┠",
            (Left, Pos(_), Rounded) => "┠",
            (Left, Pos(_), Double) => "┣",
            (Left, Pos(_), Thick) => "┣",
            (Left, Pos(_), QuadrantInside) => "┣",
            (Left, Pos(_), QuadrantOutside) => "┣",
            (Left, End, Plain) => "┗",
            (Left, End, Rounded) => "┗",
            (Left, End, Double) => "┗",
            (Left, End, Thick) => "┗",
            (Left, End, QuadrantInside) => "┗",
            (Left, End, QuadrantOutside) => "┗",
            (Left, ProlongEnd, Plain) => "┗",
            (Left, ProlongEnd, Rounded) => "┗",
            (Left, ProlongEnd, Double) => "┗",
            (Left, ProlongEnd, Thick) => "┗",
            (Left, ProlongEnd, QuadrantInside) => "┗",
            (Left, ProlongEnd, QuadrantOutside) => "┗",
        }
    } else if joint.scale == JointScale::Through {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┏",
            (Top, ProlongStart, Rounded) => "┏",
            (Top, ProlongStart, Double) => "┏",
            (Top, ProlongStart, Thick) => "┏",
            (Top, ProlongStart, QuadrantInside) => "┏",
            (Top, ProlongStart, QuadrantOutside) => "┏",
            (Top, Start, Plain) => "┏",
            (Top, Start, Rounded) => "┏",
            (Top, Start, Double) => "┏",
            (Top, Start, Thick) => "┏",
            (Top, Start, QuadrantInside) => "┏",
            (Top, Start, QuadrantOutside) => "┏",
            (Top, Pos(_), Plain) => "┿",
            (Top, Pos(_), Rounded) => "┿",
            (Top, Pos(_), Double) => "╋",
            (Top, Pos(_), Thick) => "╋",
            (Top, Pos(_), QuadrantInside) => "╋",
            (Top, Pos(_), QuadrantOutside) => "╋",
            (Top, End, Plain) => "┓",
            (Top, End, Rounded) => "┓",
            (Top, End, Double) => "┓",
            (Top, End, Thick) => "┓",
            (Top, End, QuadrantInside) => "┓",
            (Top, End, QuadrantOutside) => "┓",
            (Top, ProlongEnd, Plain) => "┓",
            (Top, ProlongEnd, Rounded) => "┓",
            (Top, ProlongEnd, Double) => "┓",
            (Top, ProlongEnd, Thick) => "┓",
            (Top, ProlongEnd, QuadrantInside) => "┓",
            (Top, ProlongEnd, QuadrantOutside) => "┓",

            (Right, ProlongStart, Plain) => "┓",
            (Right, ProlongStart, Rounded) => "┓",
            (Right, ProlongStart, Double) => "┓",
            (Right, ProlongStart, Thick) => "┓",
            (Right, ProlongStart, QuadrantInside) => "┓",
            (Right, ProlongStart, QuadrantOutside) => "┓",
            (Right, Start, Plain) => "┓",
            (Right, Start, Rounded) => "┓",
            (Right, Start, Double) => "┓",
            (Right, Start, Thick) => "┓",
            (Right, Start, QuadrantInside) => "┓",
            (Right, Start, QuadrantOutside) => "┓",
            (Right, Pos(_), Plain) => "╂",
            (Right, Pos(_), Rounded) => "╂",
            (Right, Pos(_), Double) => "╋",
            (Right, Pos(_), Thick) => "╋",
            (Right, Pos(_), QuadrantInside) => "╋",
            (Right, Pos(_), QuadrantOutside) => "╋",
            (Right, End, Plain) => "┛",
            (Right, End, Rounded) => "┛",
            (Right, End, Double) => "┛",
            (Right, End, Thick) => "┛",
            (Right, End, QuadrantInside) => "┛",
            (Right, End, QuadrantOutside) => "┛",
            (Right, ProlongEnd, Plain) => "┛",
            (Right, ProlongEnd, Rounded) => "┛",
            (Right, ProlongEnd, Double) => "┛",
            (Right, ProlongEnd, Thick) => "┛",
            (Right, ProlongEnd, QuadrantInside) => "┛",
            (Right, ProlongEnd, QuadrantOutside) => "┛",

            (Bottom, ProlongStart, Plain) => "┗",
            (Bottom, ProlongStart, Rounded) => "┗",
            (Bottom, ProlongStart, Double) => "┗",
            (Bottom, ProlongStart, Thick) => "┗",
            (Bottom, ProlongStart, QuadrantInside) => "┗",
            (Bottom, ProlongStart, QuadrantOutside) => "┗",
            (Bottom, Start, Plain) => "┗",
            (Bottom, Start, Rounded) => "┗",
            (Bottom, Start, Double) => "┗",
            (Bottom, Start, Thick) => "┗",
            (Bottom, Start, QuadrantInside) => "┗",
            (Bottom, Start, QuadrantOutside) => "┗",
            (Bottom, Pos(_), Plain) => "┿",
            (Bottom, Pos(_), Rounded) => "┿",
            (Bottom, Pos(_), Double) => "╋",
            (Bottom, Pos(_), Thick) => "╋",
            (Bottom, Pos(_), QuadrantInside) => "╋",
            (Bottom, Pos(_), QuadrantOutside) => "╋",
            (Bottom, End, Plain) => "┛",
            (Bottom, End, Rounded) => "┛",
            (Bottom, End, Double) => "┛",
            (Bottom, End, Thick) => "┛",
            (Bottom, End, QuadrantInside) => "┛",
            (Bottom, End, QuadrantOutside) => "┛",
            (Bottom, ProlongEnd, Plain) => "┛",
            (Bottom, ProlongEnd, Rounded) => "┛",
            (Bottom, ProlongEnd, Double) => "┛",
            (Bottom, ProlongEnd, Thick) => "┛",
            (Bottom, ProlongEnd, QuadrantInside) => "┛",
            (Bottom, ProlongEnd, QuadrantOutside) => "┛",

            (Left, ProlongStart, Plain) => "┏",
            (Left, ProlongStart, Rounded) => "┏",
            (Left, ProlongStart, Double) => "┏",
            (Left, ProlongStart, Thick) => "┏",
            (Left, ProlongStart, QuadrantInside) => "┏",
            (Left, ProlongStart, QuadrantOutside) => "┏",
            (Left, Start, Plain) => "┏",
            (Left, Start, Rounded) => "┏",
            (Left, Start, Double) => "┏",
            (Left, Start, Thick) => "┏",
            (Left, Start, QuadrantInside) => "┏",
            (Left, Start, QuadrantOutside) => "┏",
            (Left, Pos(_), Plain) => "╂",
            (Left, Pos(_), Rounded) => "╂",
            (Left, Pos(_), Double) => "╋",
            (Left, Pos(_), Thick) => "╋",
            (Left, Pos(_), QuadrantInside) => "╋",
            (Left, Pos(_), QuadrantOutside) => "╋",
            (Left, End, Plain) => "┗",
            (Left, End, Rounded) => "┗",
            (Left, End, Double) => "┗",
            (Left, End, Thick) => "┗",
            (Left, End, QuadrantInside) => "┗",
            (Left, End, QuadrantOutside) => "┗",
            (Left, ProlongEnd, Plain) => "┗",
            (Left, ProlongEnd, Rounded) => "┗",
            (Left, ProlongEnd, Double) => "┗",
            (Left, ProlongEnd, Thick) => "┗",
            (Left, ProlongEnd, QuadrantInside) => "┗",
            (Left, ProlongEnd, QuadrantOutside) => "┗",
        }
    } else if let JointScale::Manual(cc) = joint.scale {
        cc
    } else {
        unreachable!()
    }
}

fn quad_inside_joint(joint: Joint) -> &'static str {
    use BorderType::*;
    use JointPos::*;
    use JointSide::*;

    if joint.scale == JointScale::Out {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "▄",
            (Top, ProlongStart, Rounded) => "▄",
            (Top, ProlongStart, Double) => "▄",
            (Top, ProlongStart, Thick) => "▄",
            (Top, ProlongStart, QuadrantInside) => "▄",
            (Top, ProlongStart, QuadrantOutside) => "▄",
            (Top, Start, Plain) => "▐",
            (Top, Start, Rounded) => "▐",
            (Top, Start, Double) => "▐",
            (Top, Start, Thick) => "▐",
            (Top, Start, QuadrantInside) => "▐",
            (Top, Start, QuadrantOutside) => "▐",
            (Top, Pos(_), Plain) => "┴",
            (Top, Pos(_), Rounded) => "┴",
            (Top, Pos(_), Double) => "╨",
            (Top, Pos(_), Thick) => "┸",
            (Top, Pos(_), QuadrantInside) => "X",
            (Top, Pos(_), QuadrantOutside) => "X",
            (Top, End, Plain) => "┤",
            (Top, End, Rounded) => "┤",
            (Top, End, Double) => "┤",
            (Top, End, Thick) => "┦",
            (Top, End, QuadrantInside) => "X",
            (Top, End, QuadrantOutside) => "X",
            (Top, ProlongEnd, Plain) => "┬",
            (Top, ProlongEnd, Rounded) => "┬",
            (Top, ProlongEnd, Double) => "┬",
            (Top, ProlongEnd, Thick) => "┮",
            (Top, ProlongEnd, QuadrantInside) => "X",
            (Top, ProlongEnd, QuadrantOutside) => "X",

            (Right, ProlongStart, Plain) => "┤",
            (Right, ProlongStart, Rounded) => "┤",
            (Right, ProlongStart, Double) => "┤",
            (Right, ProlongStart, Thick) => "┦",
            (Right, ProlongStart, QuadrantInside) => "X",
            (Right, ProlongStart, QuadrantOutside) => "X",
            (Right, Start, Plain) => "┬",
            (Right, Start, Rounded) => "┬",
            (Right, Start, Double) => "┬",
            (Right, Start, Thick) => "┮",
            (Right, Start, QuadrantInside) => "X",
            (Right, Start, QuadrantOutside) => "X",
            (Right, Pos(_), Plain) => "├",
            (Right, Pos(_), Rounded) => "├",
            (Right, Pos(_), Double) => "╞",
            (Right, Pos(_), Thick) => "┝",
            (Right, Pos(_), QuadrantInside) => "X",
            (Right, Pos(_), QuadrantOutside) => "X",
            (Right, End, Plain) => "┴",
            (Right, End, Rounded) => "┴",
            (Right, End, Double) => "┴",
            (Right, End, Thick) => "┶",
            (Right, End, QuadrantInside) => "X",
            (Right, End, QuadrantOutside) => "X",
            (Right, ProlongEnd, Plain) => "┤",
            (Right, ProlongEnd, Rounded) => "┤",
            (Right, ProlongEnd, Double) => "┤",
            (Right, ProlongEnd, Thick) => "┧",
            (Right, ProlongEnd, QuadrantInside) => "X",
            (Right, ProlongEnd, QuadrantOutside) => "X",

            (Bottom, ProlongStart, Plain) => "┴",
            (Bottom, ProlongStart, Rounded) => "┴",
            (Bottom, ProlongStart, Double) => "┴",
            (Bottom, ProlongStart, Thick) => "┵",
            (Bottom, ProlongStart, QuadrantInside) => "X",
            (Bottom, ProlongStart, QuadrantOutside) => "X",
            (Bottom, Start, Plain) => "├",
            (Bottom, Start, Rounded) => "├",
            (Bottom, Start, Double) => "├",
            (Bottom, Start, Thick) => "┟",
            (Bottom, Start, QuadrantInside) => "X",
            (Bottom, Start, QuadrantOutside) => "X",
            (Bottom, Pos(_), Plain) => "┬",
            (Bottom, Pos(_), Rounded) => "┬",
            (Bottom, Pos(_), Double) => "╥",
            (Bottom, Pos(_), Thick) => "┰",
            (Bottom, Pos(_), QuadrantInside) => "X",
            (Bottom, Pos(_), QuadrantOutside) => "X",
            (Bottom, End, Plain) => "┤",
            (Bottom, End, Rounded) => "┤",
            (Bottom, End, Double) => "┤",
            (Bottom, End, Thick) => "┧",
            (Bottom, End, QuadrantInside) => "X",
            (Bottom, End, QuadrantOutside) => "X",
            (Bottom, ProlongEnd, Plain) => "┴",
            (Bottom, ProlongEnd, Rounded) => "┴",
            (Bottom, ProlongEnd, Double) => "┴",
            (Bottom, ProlongEnd, Thick) => "┶",
            (Bottom, ProlongEnd, QuadrantInside) => "X",
            (Bottom, ProlongEnd, QuadrantOutside) => "X",

            (Left, ProlongStart, Plain) => "├",
            (Left, ProlongStart, Rounded) => "├",
            (Left, ProlongStart, Double) => "├",
            (Left, ProlongStart, Thick) => "┞",
            (Left, ProlongStart, QuadrantInside) => "X",
            (Left, ProlongStart, QuadrantOutside) => "X",
            (Left, Start, Plain) => "┬",
            (Left, Start, Rounded) => "┬",
            (Left, Start, Double) => "┬",
            (Left, Start, Thick) => "┭",
            (Left, Start, QuadrantInside) => "X",
            (Left, Start, QuadrantOutside) => "X",
            (Left, Pos(_), Plain) => "┤",
            (Left, Pos(_), Rounded) => "┤",
            (Left, Pos(_), Double) => "╡",
            (Left, Pos(_), Thick) => "┥",
            (Left, Pos(_), QuadrantInside) => "X",
            (Left, Pos(_), QuadrantOutside) => "X",
            (Left, End, Plain) => "┴",
            (Left, End, Rounded) => "┴",
            (Left, End, Double) => "┴",
            (Left, End, Thick) => "┵",
            (Left, End, QuadrantInside) => "X",
            (Left, End, QuadrantOutside) => "X",
            (Left, ProlongEnd, Plain) => "├",
            (Left, ProlongEnd, Rounded) => "├",
            (Left, ProlongEnd, Double) => "├",
            (Left, ProlongEnd, Thick) => "┟",
            (Left, ProlongEnd, QuadrantInside) => "X",
            (Left, ProlongEnd, QuadrantOutside) => "X",
        }
    } else if joint.scale == JointScale::In {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┌",
            (Top, ProlongStart, Rounded) => "┌",
            (Top, ProlongStart, Double) => "┌",
            (Top, ProlongStart, Thick) => "┌",
            (Top, ProlongStart, QuadrantInside) => "X",
            (Top, ProlongStart, QuadrantOutside) => "X",
            (Top, Start, Plain) => "┌",
            (Top, Start, Rounded) => "┌",
            (Top, Start, Double) => "┌",
            (Top, Start, Thick) => "┌",
            (Top, Start, QuadrantInside) => "X",
            (Top, Start, QuadrantOutside) => "X",
            (Top, Pos(_), Plain) => "┬",
            (Top, Pos(_), Rounded) => "┬",
            (Top, Pos(_), Double) => "╥",
            (Top, Pos(_), Thick) => "┰",
            (Top, Pos(_), QuadrantInside) => "X",
            (Top, Pos(_), QuadrantOutside) => "X",
            (Top, End, Plain) => "┐",
            (Top, End, Rounded) => "┐",
            (Top, End, Double) => "┐",
            (Top, End, Thick) => "┐",
            (Top, End, QuadrantInside) => "X",
            (Top, End, QuadrantOutside) => "X",
            (Top, ProlongEnd, Plain) => "┐",
            (Top, ProlongEnd, Rounded) => "┐",
            (Top, ProlongEnd, Double) => "┐",
            (Top, ProlongEnd, Thick) => "┐",
            (Top, ProlongEnd, QuadrantInside) => "X",
            (Top, ProlongEnd, QuadrantOutside) => "X",

            (Right, ProlongStart, Plain) => "┐",
            (Right, ProlongStart, Rounded) => "┐",
            (Right, ProlongStart, Double) => "┐",
            (Right, ProlongStart, Thick) => "┐",
            (Right, ProlongStart, QuadrantInside) => "X",
            (Right, ProlongStart, QuadrantOutside) => "X",
            (Right, Start, Plain) => "┐",
            (Right, Start, Rounded) => "┐",
            (Right, Start, Double) => "┐",
            (Right, Start, Thick) => "┐",
            (Right, Start, QuadrantInside) => "X",
            (Right, Start, QuadrantOutside) => "X",
            (Right, Pos(_), Plain) => "┤",
            (Right, Pos(_), Rounded) => "┤",
            (Right, Pos(_), Double) => "╡",
            (Right, Pos(_), Thick) => "┥",
            (Right, Pos(_), QuadrantInside) => "X",
            (Right, Pos(_), QuadrantOutside) => "X",
            (Right, End, Plain) => "┘",
            (Right, End, Rounded) => "┘",
            (Right, End, Double) => "┘",
            (Right, End, Thick) => "┘",
            (Right, End, QuadrantInside) => "X",
            (Right, End, QuadrantOutside) => "X",
            (Right, ProlongEnd, Plain) => "┘",
            (Right, ProlongEnd, Rounded) => "┘",
            (Right, ProlongEnd, Double) => "┘",
            (Right, ProlongEnd, Thick) => "┘",
            (Right, ProlongEnd, QuadrantInside) => "X",
            (Right, ProlongEnd, QuadrantOutside) => "X",

            (Bottom, ProlongStart, Plain) => "└",
            (Bottom, ProlongStart, Rounded) => "└",
            (Bottom, ProlongStart, Double) => "└",
            (Bottom, ProlongStart, Thick) => "└",
            (Bottom, ProlongStart, QuadrantInside) => "X",
            (Bottom, ProlongStart, QuadrantOutside) => "X",
            (Bottom, Start, Plain) => "└",
            (Bottom, Start, Rounded) => "└",
            (Bottom, Start, Double) => "└",
            (Bottom, Start, Thick) => "└",
            (Bottom, Start, QuadrantInside) => "X",
            (Bottom, Start, QuadrantOutside) => "X",
            (Bottom, Pos(_), Plain) => "┴",
            (Bottom, Pos(_), Rounded) => "┴",
            (Bottom, Pos(_), Double) => "╨",
            (Bottom, Pos(_), Thick) => "┸",
            (Bottom, Pos(_), QuadrantInside) => "X",
            (Bottom, Pos(_), QuadrantOutside) => "X",
            (Bottom, End, Plain) => "┘",
            (Bottom, End, Rounded) => "┘",
            (Bottom, End, Double) => "┘",
            (Bottom, End, Thick) => "┘",
            (Bottom, End, QuadrantInside) => "X",
            (Bottom, End, QuadrantOutside) => "X",
            (Bottom, ProlongEnd, Plain) => "┘",
            (Bottom, ProlongEnd, Rounded) => "┘",
            (Bottom, ProlongEnd, Double) => "┘",
            (Bottom, ProlongEnd, Thick) => "┘",
            (Bottom, ProlongEnd, QuadrantInside) => "X",
            (Bottom, ProlongEnd, QuadrantOutside) => "X",

            (Left, ProlongStart, Plain) => "┌",
            (Left, ProlongStart, Rounded) => "┌",
            (Left, ProlongStart, Double) => "┌",
            (Left, ProlongStart, Thick) => "┌",
            (Left, ProlongStart, QuadrantInside) => "X",
            (Left, ProlongStart, QuadrantOutside) => "X",
            (Left, Start, Plain) => "┌",
            (Left, Start, Rounded) => "┌",
            (Left, Start, Double) => "┌",
            (Left, Start, Thick) => "┌",
            (Left, Start, QuadrantInside) => "X",
            (Left, Start, QuadrantOutside) => "X",
            (Left, Pos(_), Plain) => "├",
            (Left, Pos(_), Rounded) => "├",
            (Left, Pos(_), Double) => "╞",
            (Left, Pos(_), Thick) => "┝",
            (Left, Pos(_), QuadrantInside) => "X",
            (Left, Pos(_), QuadrantOutside) => "X",
            (Left, End, Plain) => "└",
            (Left, End, Rounded) => "└",
            (Left, End, Double) => "└",
            (Left, End, Thick) => "└",
            (Left, End, QuadrantInside) => "X",
            (Left, End, QuadrantOutside) => "X",
            (Left, ProlongEnd, Plain) => "└",
            (Left, ProlongEnd, Rounded) => "└",
            (Left, ProlongEnd, Double) => "└",
            (Left, ProlongEnd, Thick) => "└",
            (Left, ProlongEnd, QuadrantInside) => "X",
            (Left, ProlongEnd, QuadrantOutside) => "X",
        }
    } else if joint.scale == JointScale::Through {
        match (joint.side, joint.pos, joint.border) {
            (Top, ProlongStart, Plain) => "┌",
            (Top, ProlongStart, Rounded) => "┌",
            (Top, ProlongStart, Double) => "┌",
            (Top, ProlongStart, Thick) => "┌",
            (Top, ProlongStart, QuadrantInside) => "X",
            (Top, ProlongStart, QuadrantOutside) => "X",
            (Top, Start, Plain) => "┌",
            (Top, Start, Rounded) => "┌",
            (Top, Start, Double) => "┌",
            (Top, Start, Thick) => "┌",
            (Top, Start, QuadrantInside) => "X",
            (Top, Start, QuadrantOutside) => "X",
            (Top, Pos(_), Plain) => "┼",
            (Top, Pos(_), Rounded) => "┼",
            (Top, Pos(_), Double) => "╫",
            (Top, Pos(_), Thick) => "╂",
            (Top, Pos(_), QuadrantInside) => "X",
            (Top, Pos(_), QuadrantOutside) => "X",
            (Top, End, Plain) => "┐",
            (Top, End, Rounded) => "┐",
            (Top, End, Double) => "┐",
            (Top, End, Thick) => "┐",
            (Top, End, QuadrantInside) => "X",
            (Top, End, QuadrantOutside) => "X",
            (Top, ProlongEnd, Plain) => "┐",
            (Top, ProlongEnd, Rounded) => "┐",
            (Top, ProlongEnd, Double) => "┐",
            (Top, ProlongEnd, Thick) => "┐",
            (Top, ProlongEnd, QuadrantInside) => "X",
            (Top, ProlongEnd, QuadrantOutside) => "X",

            (Right, ProlongStart, Plain) => "┐",
            (Right, ProlongStart, Rounded) => "┐",
            (Right, ProlongStart, Double) => "┐",
            (Right, ProlongStart, Thick) => "┐",
            (Right, ProlongStart, QuadrantInside) => "X",
            (Right, ProlongStart, QuadrantOutside) => "X",
            (Right, Start, Plain) => "┐",
            (Right, Start, Rounded) => "┐",
            (Right, Start, Double) => "┐",
            (Right, Start, Thick) => "┐",
            (Right, Start, QuadrantInside) => "X",
            (Right, Start, QuadrantOutside) => "X",
            (Right, Pos(_), Plain) => "┼",
            (Right, Pos(_), Rounded) => "┼",
            (Right, Pos(_), Double) => "╪",
            (Right, Pos(_), Thick) => "┿",
            (Right, Pos(_), QuadrantInside) => "X",
            (Right, Pos(_), QuadrantOutside) => "X",
            (Right, End, Plain) => "┘",
            (Right, End, Rounded) => "┘",
            (Right, End, Double) => "┘",
            (Right, End, Thick) => "┘",
            (Right, End, QuadrantInside) => "X",
            (Right, End, QuadrantOutside) => "X",
            (Right, ProlongEnd, Plain) => "┘",
            (Right, ProlongEnd, Rounded) => "┘",
            (Right, ProlongEnd, Double) => "┘",
            (Right, ProlongEnd, Thick) => "┘",
            (Right, ProlongEnd, QuadrantInside) => "X",
            (Right, ProlongEnd, QuadrantOutside) => "X",

            (Bottom, ProlongStart, Plain) => "└",
            (Bottom, ProlongStart, Rounded) => "└",
            (Bottom, ProlongStart, Double) => "└",
            (Bottom, ProlongStart, Thick) => "└",
            (Bottom, ProlongStart, QuadrantInside) => "X",
            (Bottom, ProlongStart, QuadrantOutside) => "X",
            (Bottom, Start, Plain) => "└",
            (Bottom, Start, Rounded) => "└",
            (Bottom, Start, Double) => "└",
            (Bottom, Start, Thick) => "└",
            (Bottom, Start, QuadrantInside) => "X",
            (Bottom, Start, QuadrantOutside) => "X",
            (Bottom, Pos(_), Plain) => "┼",
            (Bottom, Pos(_), Rounded) => "┼",
            (Bottom, Pos(_), Double) => "╫",
            (Bottom, Pos(_), Thick) => "╂",
            (Bottom, Pos(_), QuadrantInside) => "X",
            (Bottom, Pos(_), QuadrantOutside) => "X",
            (Bottom, End, Plain) => "┘",
            (Bottom, End, Rounded) => "┘",
            (Bottom, End, Double) => "┘",
            (Bottom, End, Thick) => "┘",
            (Bottom, End, QuadrantInside) => "X",
            (Bottom, End, QuadrantOutside) => "X",
            (Bottom, ProlongEnd, Plain) => "┘",
            (Bottom, ProlongEnd, Rounded) => "┘",
            (Bottom, ProlongEnd, Double) => "┘",
            (Bottom, ProlongEnd, Thick) => "┘",
            (Bottom, ProlongEnd, QuadrantInside) => "X",
            (Bottom, ProlongEnd, QuadrantOutside) => "X",

            (Left, ProlongStart, Plain) => "┌",
            (Left, ProlongStart, Rounded) => "┌",
            (Left, ProlongStart, Double) => "┌",
            (Left, ProlongStart, Thick) => "┌",
            (Left, ProlongStart, QuadrantInside) => "X",
            (Left, ProlongStart, QuadrantOutside) => "X",
            (Left, Start, Plain) => "┌",
            (Left, Start, Rounded) => "┌",
            (Left, Start, Double) => "┌",
            (Left, Start, Thick) => "┌",
            (Left, Start, QuadrantInside) => "X",
            (Left, Start, QuadrantOutside) => "X",
            (Left, Pos(_), Plain) => "┼",
            (Left, Pos(_), Rounded) => "┼",
            (Left, Pos(_), Double) => "╪",
            (Left, Pos(_), Thick) => "┿",
            (Left, Pos(_), QuadrantInside) => "X",
            (Left, Pos(_), QuadrantOutside) => "X",
            (Left, End, Plain) => "└",
            (Left, End, Rounded) => "└",
            (Left, End, Double) => "└",
            (Left, End, Thick) => "└",
            (Left, End, QuadrantInside) => "X",
            (Left, End, QuadrantOutside) => "X",
            (Left, ProlongEnd, Plain) => "└",
            (Left, ProlongEnd, Rounded) => "└",
            (Left, ProlongEnd, Double) => "└",
            (Left, ProlongEnd, Thick) => "└",
            (Left, ProlongEnd, QuadrantInside) => "X",
            (Left, ProlongEnd, QuadrantOutside) => "X",
        }
    } else if let JointScale::Manual(cc) = joint.scale {
        cc
    } else {
        unreachable!()
    }
}
